### ISSUE TITLE
"push to application" changes to LyX at every start

### ISSUE THREAD

**Issue by koppor** [koppor/jabref#1]
The "puash to application" button should keep the last selected application.

The default preferences should point to TeXstudio, not to LyX.

**Comment by oscargus** [comment]
The reason it doesn't work is that the string "Insert selected citations into %d" is not translated. However, there are some other small things which can/should be improved (including not relying on translation of a string), so a PR is on the way.

**Comment by koppor** [comment]
Fixed in master. Thank you.
