### ISSUE TITLE
Better escaping in SQL export

### ISSUE THREAD

**Issue by oscargus** [koppor/jabref#100]
Currently, there are errors when exporting some characters (typically HTML tags) to a PostgreSQL database. Ideally these should be escaped in a way such that it doesn't happen. If nothing else it would be useful if the problematic entry is identified.

**Comment by koppor** [comment]
First thought: JabRef should switch to [prepared statements](https://en.wikipedia.org/wiki/Prepared_statement).

**Comment by simonharrer** [comment]
Already done
