### ISSUE TITLE
Improvements to the autocompleter ui

### ISSUE THREAD

**Issue by tobiasdiez** [koppor/jabref#108]
We might consider to add the following:
- Autocompleter dropdown should appear if the search field gets the focus and some text is already entered.
- Add some shadow to the dropdown to set it better apart from the background. As here
  ![OneNote](http://captaintime.com/wp-content/uploads/2015/10/OneNote-Search1.jpg)
- The global search result should use the same style as the main table.

**Comment by koppor** [comment]
Reading https://github.com/JabRef/jabref/issues/6305, this is obsolete.

https://baymard.com/blog/autocomplete-design

![grafik](https://user-images.githubusercontent.com/1366654/92049907-f717f180-ed8b-11ea-9dc7-7454413f6afc.png)

(even if I find that uncommon)

![grafik](https://user-images.githubusercontent.com/1366654/92049897-f1221080-ed8b-11ea-95f0-a72c84228281.png)
