### ISSUE TITLE
When an entry is added at the beginning of the .bib file, there are no newlines appended

### ISSUE THREAD

**Issue by koppor** [koppor/jabref#114]
![grabbed_20151214-110539](https://cloud.githubusercontent.com/assets/1366654/11778095/9f2ce676-a252-11e5-8217-94f0792469af.png)

**Comment by lenhard** [comment]
We decided to always add new entries to the bottom of the file. Once this is implemented, also that problem should disappear.

**Comment by lenhard** [comment]
I implemented a small tweak to the serialization in 10cce523ebeb2bb3919c4abe0d5567a235e693ba The newlines between the file header and the first entry are now stored as part of the parsed serialization of the first entry. This fixes this issue (works for me, please double-check). 

However, this means that the newline between the first entry and the preamble "move", together with the first entry. So if you have five newlines between the first entry and the preamble and resort the file, the five newlines move together with the first entry. From my point of view, this is a feature, not a bug :smile:

**Comment by tobiasdiez** [comment]
I think this is solved.

**Comment by lenhard** [comment]
Agreed.
