### ISSUE TITLE
bib per pdf

### ISSUE THREAD

**Issue by koppor** [koppor/jabref#121]
Currently, one maintains a large bib file and has PDFs linked. Why not having a `bib` file per `pdf` and JabRef puts these together?

Example:

```
MPT2006 - Implicit vs. Explicit Data-Flow Requirements - ICSOC2006.pdf
MPT2006 - Implicit vs. Explicit Data-Flow Requirements - ICSOC2006.bib
```

A bibliography is then a directory. It would be OK to put a "meta.bib" in the root folder. This meta.bib contains necessary meta data.

This approach is alternative to store all bib data in each PDF.

**Comment by tobiasdiez** [comment]
But there is nearly no support for such a storage format from the latex side (biber/bibtex), right?

**Comment by koppor** [comment]
In biblatex, I can integrate multiple bib files, can't I?

Maybe, the better approach is to move to dublin core (see https://github.com/JabRef/jabref/issues/938#issuecomment-195459251) and to store the bib entry in the PDF itself. This might, however, be problematic in write-protected PDFs.
