### ISSUE TITLE
Remove serialVersionUID?

### ISSUE THREAD

**Issue by oscargus** [koppor/jabref#13]
In some earlier commits I introduced serialVersionUID:s (and I think someone else did the same), just to later find out that the warning wasn't really important.

Is it worthwhile removing these?

**Comment by koppor** [comment]
Sure, please remove all of them. They should only be put if absolutely necessary.

**Comment by stefan-kolb** [comment]
https://github.com/JabRef/jabref/commit/0888a8a5fce7f47a54548443deb99a0b3f38a4a0

**Comment by oscargus** [comment]
:+1:
