### ISSUE TITLE
Add support for date-added and date-modified

### ISSUE THREAD

**Issue by koppor** [koppor/jabref#130]
There seem to exist a bibtex tool producing following data:

```
Date-Added = {2015-04-29 11:46:47 +0000},
Date-Modified = {2015-04-29 11:48:44 +0000},
```

In JabRef, we have `timestamp`.

We should migrate to `date-...`, because `date-...` has more semantics.

@pautasso It seems, this is from you, isn't it? Which tool are you using? :innocent: 

(extract from https://github.com/JabRef/jabref/issues/995)

```
  date-added =    {2014-02-17 12:06:22 +0000},
  date-modified = {2015-06-02 20:04:28 +0000},
```

I currently don't know, which software writes these data fields. I think, however, that we should migrate from `timestamp` to `date-*` as the semantics of `timestamp` is not clear at first sight: Is it the timestamp of the last modification or the timestamp of the creation? Furthermore: Why is no time included? Furthermore: Why is no ISO date used?

**Comment by oscargus** [comment]
Also note that `timestamp` is just the default value and can be changed in the preferences.

**Comment by tobiasdiez** [comment]
Note that dates in biblatex always ends on `date`, like `eventdate`, `urldate` or `origdate`. The reason for this convention is that biblatex automatically parses these dates and provides virtual fields containing the information like `eventmonth` or `eventyear`. See `\DeclareLabeldate` command. Thus I would propose 
- `creationdate`
- `modificationdate`

By the way, I think BibDesk writes `date-added` and `date-modified`.

**Comment by oscargus** [comment]
Although what you say makes sense @tobiasdiez , the question is if we should introduce yet anotherfield name. I would suspect that these field are not so interesting from a bibliography generation perspective as from a bibliography management perspective anyway.

How will BibLatex deal with time in a `*date`-field?

**Comment by koppor** [comment]
dblp exports

    timestamp = {Tue, 12 Jan 2016 12:01:53 +0100},

Maybe that should be supported in addition?

**Comment by koppor** [comment]
We support `timestamp` out of the box: https://docs.jabref.org/advanced/entryeditor/timestamp#usage

**Comment by koppor** [comment]
It can be configured properly:

![grafik](https://user-images.githubusercontent.com/1366654/103486238-b1803980-4dfc-11eb-9d97-8946986fd4c2.png)

Proposal:

- Add migration:
  - In case "update timestamp on modification" is not activated: rename `timestamp` to `date-added` in the .bib file. Update timestamp with time `00:00` and `+00:00`.
  - In case "update timestamp on modification" is activated: rename `timestamp` to `date-modified` in the .bib file. Update timestamp with time `00:00` and `+00:00`.
- Rename configuration "Mark new entries with addition date" to "`Add timestamp to new entries (field "date-added")`"
- Add configuration "`Add timestamp to modified entries (field "date-modified")`"
- Remove configurations: "Mark new entries with addition date", "Date format", "Field name", "Overwrite", "Update timestamp on modification"
- "Overwrite" is always active: In case an entry is added to a database, it receives a new time stamp even if a timestamp is present

**Comment by koppor** [comment]
Implementd at #7334 with `creationdate` and `modificationdate`.
