### ISSUE TITLE
Replace java-string-similarity library

### ISSUE THREAD

**Issue by koppor** [koppor/jabref#131]
We currently use https://github.com/tdebatty/java-string-similarity for the Levenshtein distance. This function is [also offered by Apache Commons Lang 3](https://commons.apache.org/proper/commons-lang/apidocs/org/apache/commons/lang3/StringUtils.html#getLevenshteinDistance(java.lang.CharSequence,%20java.lang.CharSequence)). To ease packaging in Linux distributions, I would propose to switch from the mostly unpackaged library to Apache Commons Lang3.

**Comment by oscargus** [comment]
There is also a version `DuplicateCheck`.

**Comment by koppor** [comment]
Not necessary any more: Debian offers a recent version of it https://tracker.debian.org/pkg/java-string-similarity. I think, no other linux distribution will have issues, so, I can close this.
