### ISSUE TITLE
Reformat all entries

### ISSUE THREAD

**Issue by koppor** [koppor/jabref#139]
JabRef should offer a button to reformat all entries.

Current solution: set field `clean` to `clean` and then clear field `clean`.

**Comment by matthiasgeiger** [comment]
Implementation: just mark all entries as "changed" by calling `setChanged(boolean changed)` on all entries.

**Comment by koppor** [comment]
Another workaround: "Always reformat on save"

![image](https://github.com/koppor/jabref/assets/1366654/70f4410a-0929-4aae-9d74-7da47aaad599)

Think, this could be a nice CLI feature, but not high priority. Thus closing this issue.
