### ISSUE TITLE
JavaFX

### ISSUE THREAD

**Issue by koppor** [koppor/jabref#143]
- [x] Check if CLI still works. If not rewrite so that command line is started using JavaFX mechansims (@JabRef/StuPro)
- [x] Check if JabRef can still be packaged using Install4J (@koppor)
- [x] Check that it runs under most linux distributions (@JabRef/StuPro)

**Comment by koppor** [comment]
[openjfx](http://packages.ubuntu.com/search?keywords=openjfx) seems to be the package for Ubuntu

`xenial (java): JavaFX/OpenJFX 8 - Rich client application platform for Java [universe] 8u60-b27-4`

**Comment by boceckts** [comment]
On Ubuntu I would also test oracle jdk. [Oracle JDK](https://wiki.ubuntuusers.de/Java/Installation/Oracle_Java/Java_8/#Java-8-JDK) can be installed quite easily and doesn't need any additional libraries. The the jdks can be switched by using `sudo update-alternatives --config java`

**Comment by bruehldev** [comment]
Thanks a lot, i will additionally add  some test cases in the  test protocol for openjfx.
Is there a simple solution to test install4j without installing the framework?
Somehow i can't run install4j. Not even on the upstream master branch. 
I got this error message: 
* 
What went wrong:
Execution failed for task ':install4j'.
> property "projectFile" must be set
*
Where can i set this property?

**Comment by koppor** [comment]
Install4J can only tested by the developers of JabRef. It is automatically built if someone pushes to a branch at http://github.com/JabRef/jabref/. Then, it is available at https://builds.jabref.org/ `<branchname>`. In our case soon at https://builds.jabref.org/javafx/

Regarding your branch https://github.com/bruehldev/jabref/tree/javafxTest - could you merge in http://github.com/JabRef/jabref/javafx? (Minor thing: I could not use your branch as the CHANGELOG.md was corrupted during merge - the changelog of a released version was changed)

Before merging, could you check http://github.com/JabRef/jabref/javafx and say what could be possibly wrong there? Why so many tests are failing?

**Comment by tobiasdiez** [comment]
@koppor I think @bruehldev wants to create an installer, i.e. "release" JabRef. @bruehldev did you followed the steps outlined in the wiki?

**Comment by bruehldev** [comment]
@koppor. I had the same issues on my branch and it's getting worse after the merge with the upstream/master branch. Most of the test's fail with with the error message: 

net.sf.jabref.logic.cleanup.CleanupWorkerTest > cleanupCasesAddsBracketAroundAluminiumGalliumArsenid FAILED
   java.lang.NoClassDefFoundError: Could not initialize class net.sf.jabref.logic.protectedterms.ProtectedTermsLoader
       at net.sf.jabref.preferences.JabRefPreferences.<init>(JabRefPreferences.java:687)
       at net.sf.jabref.preferences.JabRefPreferences.getInstance(JabRefPreferences.java:462)
       at net.sf.jabref.logic.cleanup.CleanupWorkerTest.setUp(CleanupWorkerTest.java:53)

I tried to find the cause of the error but i couldn't so far. I will merge my branch after i finished all javafx tests. Maybe @boceckts knows more.

@braunch and me think it had something to do with 
https://github.com/JabRef/jabref/blob/javafx/src/main/java/net/sf/jabref/logic/protectedterms/ProtectedTermsLoader.java#L44

 @tobiasdiez i created a .jar file for testing by using releaseJar with gradle. I just wondered how i can integrate Install4J. It's good to know that install4j is automatically built in JabRef.

**Comment by koppor** [comment]
The `cleanupCasesAddsBracketAroundAluminiumGalliumArsenid` is fixed in the master branch (#1706)

**Comment by koppor** [comment]
Install4J can only be used by the developers of JabRef as only we have the license key. As the license key is available also on TravisCI, all builds triggered by the JabRef developers produce an installer. As soon as JabRef's javafx branch compiles, a build is produced at builds.jabref.org/javafx.

**Comment by bruehldev** [comment]
@koppor 
I ckecked the CLI on every kind of operating system and it worked perfectly .(https://github.com/bruehldev/JabRef---Javafx-production-test/blob/master/JavaFXProduktionstest.md#cli). 

I couldn't run and test the Install4J build, because there were some issues left.
If @tobiasdiez solves the last failing test in 'https://github.com/JabRef/jabref/pull/1753' i can proceed with that test.

**Comment by koppor** [comment]
JabRef 4.0 uses JavaFX.
