### ISSUE TITLE
URL and IEEEtran

### ISSUE THREAD

**Issue by oscargus** [koppor/jabref#15]
In the IEEEtran.bst the url field is (more or less) always included which is a problem since it leads to that one will have to remove it from the entries which are to be included, while at the same time it is quite convenient to have the url in the .bib database.

Some quick solution for this should be available, but I can not really figure out how.

**Comment by koppor** [comment]
This is related to https://github.com/JabRef/jabref/issues/160. I think, you are talking about having BC the URL filed and BW not.

**Comment by oscargus** [comment]
Yes, that is probably a correct observation. Except that I only want one file. :-) But I see the point of having two files and, yes, ideally that is probably a good way to work with references.

In the meanwhile, I'm still thinking of a simple way to make a .bib-file more IEEE-suitable.

**Comment by koppor** [comment]
Internally, we prefix our fields with `_` to have the data in the .bib file and to have it processable by a (unmodified :innocent:) bst file. Maybe that would work, too. Currently, I don't really like to have two files, either.

Do you think, it would be a good way to implement the `_` way? In the UI, the content is displayed normally, but there is `(h)` displayed after "Doi" do indicate that the field is hidden.

**Comment by oscargus** [comment]
Yes, that might be a solution. However, I just realized that there is a better way (for my particular use case), see #21. The field `CTLuse_url` does exactly this. The only drawback of this (and to some extent most approaches) is that one would like to do this on an entry type (if not entry) basis. For some references (such as web pages...) it makes sense to include the URL.

**Comment by koppor** [comment]
The solution of #21 seems to be for IEEE only, not for Springer etc. :cry:

**Comment by oscargus** [comment]
Correct. Not sure which other .bst:s automatically includes the url field though.

**Comment by koppor** [comment]
The springer thing is always a difficult thing. Especially, pages are included in `InProceedings` entries.

**Comment by oscargus** [comment]
I think that the current support is good enough.
