### ISSUE TITLE
Globals issues

### ISSUE THREAD

**Issue by oscargus** [koppor/jabref#150]
I thought we can use this issue to discuss issues with Globals to be solve/clarified before the "golden" architecture model is done.

* `Globals.prefs` must be initialized to create a `MetaData` instance, which affects many tests. Where should `MetaData` reside in the final architecture?
* Same holds for `BibDatabaseContext` (as it contains a `MetaData` object).

**Comment by tobiasdiez** [comment]
We already discussed it in one of the last dev calls and came to the conclusion that MetaData should be in model. So in particular no access to Globals.prefs

**Comment by oscargus** [comment]
OK! Good! What about BibDatabaseContext? Also in model?

**Comment by oscargus** [comment]
More issues:
* `InternalBibtexFields` relies on the preferences to decide how to serialize special fields `Globals.prefs.getBoolean(SpecialFieldsUtils.PREF_SERIALIZESPECIALFIELDS)` and to get the name of the time stamp field `Globals.prefs.get(JabRefPreferences.TIME_STAMP_FIELD)`. The latter is solved once we have agreed on (and implemented) the new time stamp format. The former is not so obvious (explicit initialization in `JabRefMain`, and related tests, is one solution).
* `ExportFormat` can be solved by adding a `LayoutFormatterPreferences` argument to the constructor, which can be passed to/from `ExportFormats.initAllExports`.
* `FileSaveSession` relies on  `Globals.prefs.getBoolean(JabRefPreferences.USE_LOCK_FILES)`. However, this can not be changed anywhere, so the default value of `true` is always used. Remove and always use lock files?

**Comment by oscargus** [comment]
And how should the `MetaData` issue be solved? Always pass the encoding in the constructors?

**Comment by oscargus** [comment]
BibDatabaseContext solved in https://github.com/JabRef/jabref/pull/1856

**Comment by oscargus** [comment]
I close this as both Globals, MetaData, all of main/logic is now Globals-free. Only dependency in test/logic is a for a test where ExternalFileTypes are accessed.
