### ISSUE TITLE
Browse for .aux file does not take current folder as starting folder

### ISSUE THREAD

**Issue by baderas** [koppor/jabref#153]
![jabref2](https://cloud.githubusercontent.com/assets/13378513/17560730/68c4f1e4-5f23-11e6-806b-3a1202f6c9b3.png)

**Comment by koppor** [comment]
Also at save as

Steps:
1. generate .aux file from bib
2. save the file "ohne Titel"

**Comment by Siedlerchr** [comment]
Fixed in Jabref/jabref#1336

**Comment by koppor** [comment]
Please try latest devbuild at http://builds.jabref.org/master/

**Comment by stefan-kolb** [comment]
Is fixed.
