### ISSUE TITLE
Windows version uses  old-school explorer dialog when opening files

### ISSUE THREAD

**Issue by baderas** [koppor/jabref#154]
When opening a .aux file, the explorer dialog is not the modern version with support for windows specific functions like "shortcuts" ("Schnellzugriff") etc.

**Comment by koppor** [comment]
JabRef 2.11 supported the native file dialog. See below. We once decided that it is a good idea to rely on one dialog type only. I agree that it is not intuitive for users not being offered the native file dialog. Maybe, we should always open the native one. @Siedlerchr WDYT? Maybe we should use the native one on Windows and the Java one on all other OS?

![grabbed_20160810-183543](https://cloud.githubusercontent.com/assets/1366654/17562062/4692bd58-5f29-11e6-8c98-eb28659097b9.png)

![grabbed_20160810-183616](https://cloud.githubusercontent.com/assets/1366654/17562083/6702c2fe-5f29-11e6-8435-54f68f8c02e9.png)

**Comment by Siedlerchr** [comment]
Please try again with the current master (I just merged the jabref/JabRef#1336) in

**Comment by Siedlerchr** [comment]
Swing problem. 
Seems like it is solved with javaFX:
http://docs.oracle.com/javafx/2/ui_controls/file-chooser.htm

**Comment by oscargus** [comment]
And here is a good discussion: http://stackoverflow.com/questions/5703825/does-swing-support-windows-7-style-file-choosers

**Comment by Siedlerchr** [comment]
I already created a follow up issue: JabRef/jabref/issues/1711
