### ISSUE TITLE
Preferences which are constants

### ISSUE THREAD

**Issue by oscargus** [koppor/jabref#155]
In https://github.com/JabRef/jabref/pull/1672 I removed some preferences but also found some preferences that could not be changed (except for editing the XML). Those are:

``` Java
public static final String MAX_BACK_HISTORY_SIZE = "maxBackHistorySize"; // The maximum number of "Back" operations stored. TODO: Not changeable
public static final String LINE_LENGTH = "lineLength"; // Maximum TODO: Not changeable
public static final String INDENT = "indent"; //	Indent for formatted bibtex output. TODO: Not changeable
public static final String DISPLAY_KEY_WARNING_DIALOG_AT_STARTUP = "displayKeyWarningDialogAtStartup";
public static final String USE_LOCK_FILES = "useLockFiles";
```

Should we add configuration for these? Should we move them to be constants? Should they exist as non-documented features for power users? 

Especially removing `USE_LOCK_FILES` would remove the final `Globals` dependency in `logic.exporter`, see #150.

**Comment by koppor** [comment]
Decision by JabRef/developers: Remove them, but keep the settings as constants.
