### ISSUE TITLE
Tooltips not working in the main table

### ISSUE THREAD

**Issue by oscargus** [koppor/jabref#160]
There is supposed to be a tooltip for the red incomplete entry field, from `IncompleteRenderer.java`:

``` Java
        setToolTipText(Localization.lang("This entry is incomplete"));
```

However, this is not working on either my Windows 10 laptop nor my office CentOS machine. Anyone have it working or have an idea what is wrong?

I tried the slightly different approach in http://stackoverflow.com/questions/9467093/how-to-add-a-tooltip-to-a-cell-in-a-jtable as well (applied it in `GeneralRender`) but that didn't work either.

**Comment by grimes2** [comment]
Tooltips are working only for cells, where the content is exceeding the columns width.

**Comment by oscargus** [comment]
I'm not sure (although I wish that was the explanation): http://docs.oracle.com/javase/tutorial/uiswing/components/table.html#celltooltip
