### ISSUE TITLE
Cleanup builds.jabref.org (delete merged branches)

### ISSUE THREAD

**Issue by Siedlerchr** [koppor/jabref#164]
Atm it shows man old builds, because someone accidentally restored some old already merged branches...
Well, branches are now gone, but http://builds.jabref.org/ is still cluttered with it...

@koppor  Unfortunately I have no idea where and how to cleanup.

**Comment by koppor** [comment]
Currently, this is a manual job. I tried to write a script to delete the
old ones, but didn't succeed. To delete the merged branches is a good idea.
I've got an API key and will try again. - builds.jabref.org runs on my
private server flupp.de.

**Comment by koppor** [comment]
In place since two weeks. We also generate README.md based on the pull request information. See, e.g., https://builds.jabref.org/fileDirPattern/
