### ISSUE TITLE
Master @builds.jabref.org is no longer build/updated

### ISSUE THREAD

**Issue by Siedlerchr** [koppor/jabref#165]
@koppor  The current master dev build is still from 02.09.16. In the meantime some code has been merged in, but the dev master does not get updated.

Please investigate.

**Comment by koppor** [comment]
Current status: CircleCI does not build any more - https://circleci.com/gh/JabRef/jabref

**Comment by koppor** [comment]
I deleted the web hook and added the direct integration.

I think, this could be not wanted by the JabRef developers as we don't want to have two emails if something goes wrong - TravisCI is our main test suite, CircleCI is just to enable a quick build even if the tests fail.

**Comment by koppor** [comment]
I don't find any documentation regarding `https://codecov.io/webhooks/github`. Don't know, how the right CodeCov setup should be.

**Comment by koppor** [comment]
I had to delete the integration on GitHub and the project on CircleCI. Then, I reenabled the integration on GitHub, added the project on CircleCI. Then, the webhook was installed again and CircleCI did a fresh build. It still had the old builds available.

Seems that we have the old state again.
