### ISSUE TITLE
Add citation count to each paper

### ISSUE THREAD

**Issue by koppor** [koppor/jabref#168]
I need a Google Scholar scraper which updates each paper in my bib file and adds the number of citations in the field <s>`citations`</s> `citation_count`.

**Comment by oscargus** [comment]
Is `citations` the correct name. I'm thinking about the discussion regarding linking entries (but cannot find it from the phone, sorry). Also, there are many sources for citation counts and it may be of interest to store more than one.

**Comment by koppor** [comment]
The discussion regarding the fields is made at #14.

Different sources. Maybe store as key/value? Maybe like our save order config?

**Comment by koppor** [comment]
The database mentioned at https://journals.plos.org/plosbiology/article?id=10.1371/journal.pbio.3000385 could be helpful (via https://twitter.com/egonwillighagen/status/1183974415534559234)

**Comment by koppor** [comment]
Follow-up at https://github.com/JabRef/jabref/issues/5849
