### ISSUE TITLE
Replace PDFContentImporter by another library

### ISSUE THREAD

**Issue by koppor** [koppor/jabref#169]
As user, I want to import a PDF into JabRef. Each PDF contains bibliographic information. Either by embedded XMP data or by just the txt on the title page (author, title, doi, ..., maybe included bibtex: https://www.ctan.org/pkg/coverpage or https://ctan.org/pkg/authorarchive?lang=de). This information should be extracted from the PDF.

Currently, a self-written functionality is employed. This works OK for LNCS and IEEE papers, but not for other publishers.

## Solution Sketch

We have a grobid in place. This should be used. Check Apache Tika, too.

Steps:

1. If first PDF page containts `@article` or something direct BibTeX data (created by https://www.ctan.org/pkg/coverpage).
2. Check if a `.bib` file is embedded in the PDF. If yes, use this one. (created by https://ctan.org/pkg/authorarchive?lang=de)
3. Check if XMP data is available. If yes -> use that. Stop. Else continue.
4. Look for DOI in the first page. If present -> use that. Stop. Else continue.
5. Use Apache Tika/GROBID to extract PDF. Use that data.

## Improvement possibility

Offer merge dialog from the different options (e.g., XMP + PDF scraping via GROBID)

## Challenges

- Cover different cases (BibTeX text on the first page, `.bib` embedded, DOI on first page, different publisher PDFs (LNCS, LNI, IEEE, ACM, ...)
- Good test cases
  - Create test PDFs
 
## Side notes

Check current drag'n'drop behavior. In 3.8.2, the user was asked whether (s)he wants to create a new entry or link the PDF.

In http://discourse.jabref.org/t/more-control-on-the-duplicate-finder/120/4?u=koppor the tool https://github.com/CrossRef/pdfextract was recommended. At first sight, it can fully replace our PDFContentImporter.

Refs https://github.com/JabRef/jabref/pull/7209

**Comment by tobiasdiez** [comment]
But pdfextract is a (Ruby?) program and no Java library that can easily be integrated. ?

**Comment by koppor** [comment]
Depends on the definition of "easily". https://github.com/jruby/jruby/wiki/DirectJRubyEmbedding

(i) Being the initial author of PDFContentImporter, (ii) seeing that no one took over the last years, (iii) knowing the issues and (iv) limitations of the current implementation, I think, it is more easy to integrate the library than to fix PDFContentImporter.

Side story: Colleagues from an other department use the PDFContentImporter successfully with Springer and IEEE papers. Which are the two publishers it was designed for.

**Comment by koppor** [comment]
After rereading the homepage of pdfextract, the tool seems "only" to help to extract the title of the PDF. Thus, it does not help to improve the PDFContentImporter.

**Comment by koppor** [comment]
There are questions on StackExchange asking for PDF2Bib:

  * [Is there an open source tool for producing bibtex entries from paper PDFs?](http://academia.stackexchange.com/q/15504/4186)
 * [Extracting information from PDFs of research papers]()
  * [Extract titles from each page of a PDF?](http://stackoverflow.com/q/18071127/873282)

Solutions outlined:

 * [cs2Bib](http://www.molspaces.com/d_cb2bib-overview.php)
 * [CERMINE](https://github.com/CeON/CERMINE)
 * https://code.google.com/p/pdfssa4met/
 * [pdftk](http://www.accesspdf.com/pdftk/)
 * [gscholar](https://github.com/venthur/gscholar) in combination with [pdftotext](http://en.wikipedia.org/wiki/Pdftotext)
 * [bibfetch](https://github.com/dschoepe/bibfetch)

**Comment by koppor** [comment]
Refs https://github.com/JabRef/jabref/pull/2474, https://github.com/koppor/jabref/issues/327

**Comment by koppor** [comment]
The important thing on this issue is to categorize "related work". 

- Input: Set of represantive PDFs 
- Output: 
  - BibTeX generated for each PDF
  - Quality rating

**Comment by StarTrooper08** [comment]
> There are questions on StackExchange asking for PDF2Bib:
> 
> * [Is there an open source tool for producing bibtex entries from paper PDFs?](http://academia.stackexchange.com/questions/15504/is-there-an-open-source-tool-for-producing-bibtex-entries-from-paper-pdfs)
> * [Extract titles from each page of a PDF?](http://stackoverflow.com/q/18071127/873282)
> * [Extracting information from PDFs of research papers](http://stackoverflow.com/questions/1813427/extracting-information-from-pdfs-of-research-papers/3523416)
> 
> Solutions outlined:
> 
>  * [cs2Bib](http://www.molspaces.com/d_cb2bib-overview.php)
>    * They [also have XMP support](https://codesearch.debian.net/search?q=jabref+package%3Acb2bib)
>  * [CERMINE](https://github.com/CeON/CERMINE)
>  * https://code.google.com/p/pdfssa4met/
>  * [pdftk](http://www.accesspdf.com/pdftk/)
>  * [gscholar](https://github.com/venthur/gscholar) in combination with [pdftotext](http://en.wikipedia.org/wiki/Pdftotext)
>  * [bibfetch](https://github.com/dschoepe/bibfetch)
> 
> More solutions:
> 
> * https://github.com/academia-edu/biblicit - a wrapper around the tools
> * GROBIT/GROBID - see https://github.com/koppor/jabref/issues/327
> 

Can we use python to implement pdf2bibtex convertion??
