### ISSUE TITLE
Remove key bindings for specific searches

### ISSUE THREAD

**Issue by oscargus** [koppor/jabref#17]
Currently, there are key bindings defined for the following fetches/searches:

```java
    public static final String FETCH_AR_XIV_ORG = "Fetch ArXiv.org";
    public static final String FETCH_INSPIRE = "Fetch INSPIRE";
    public static final String FETCH_MEDLINE = "Fetch Medline";
    public static final String FETCH_SPIRES = "Fetch SPIRES";
...
    public static final String SEARCH_ACM_PORTAL = "Search ACM Portal";
    public static final String SEARCH_ADS = "Search ADS";
    public static final String SEARCH_IEEE_XPLORE = "Search IEEEXplore";
    public static final String SEARCH_JSTOR = "Search JSTOR";
    public static final String SEARCH_SCIENCE_DIRECT = "Search ScienceDirect";
```

However, none of these are actually implemented in JabRef and personally, I do not see the point in have a key binding for a specific searcher/fetcher.

Hence, any objections against removing these from KeyBinds.java? They can of course easily be added in case someone implements the key binding.

**Comment by simonharrer** [comment]
:+1:

**Comment by simonharrer** [comment]
You can remove the EntryFetcher.getKeyName() method from the EntryFetcher interface as this would then be unused as well.

**Comment by koppor** [comment]
:+1:

**Comment by oscargus** [comment]
This is implemented in the latest version of the Remove KeyBinds... PR, so closing this.
