### ISSUE TITLE
Dropping a file into the file field does not shorten the path 

### ISSUE THREAD

**Issue by koppor** [koppor/jabref#178]
Setting: General file directory (of the database): `C:\Users\Oliver\BTSync\lit`

Result after dropping a file: `file   = {:C\:\\Users\\koppor\\BTSync\\lit\\IoT\\MA_Guth_JA.pdf:PDF},`
Expected: `file   = {:IoT\\MA_Guth_JA.pdf:PDF},`, because `C\:\\Users\\koppor\\BTSync` is the prefix of the filename.

I think, this worked in JabRef 2.11... Think, `FileUtils` is the class to look at. See also https://github.com/JabRef/jabref/wiki/Code-Howtos#get-absolute-filename-or-path

**Comment by Siedlerchr** [comment]
Should work with the changes I introduced in https://github.com/JabRef/jabref/pull/2415
