### ISSUE TITLE
Dirty marking does not work anymore

### ISSUE THREAD

**Issue by koppor** [koppor/jabref#180]
If I change an entry, there is no asterisk appended in the tab title.

JabRef 3.7dev--snapshot--2016-10-27--javafx--e489a53
windows 10 10.0 amd64 
Java 1.8.0_101

**Comment by matthiasgeiger** [comment]
Do you use the new autosave functionality?

**Comment by koppor** [comment]
No

![grabbed_20161101-112841](https://cloud.githubusercontent.com/assets/1366654/19887027/65d21928-a026-11e6-9ae0-d8f4c2031778.png)
