### ISSUE TITLE
FLOSS Coach pointing to the wrong issue tracker

### ISSUE THREAD

**Issue by oscargus** [koppor/jabref#19]
On http://www.flosscoach.com/index.php/my-coach/jabref it reads:

Jabref issue tracker: http://sourceforge.net/p/jabref/bugs/

**Comment by koppor** [comment]
@igorsteinmacher Can you have a look?

**Comment by igorsteinmacher** [comment]
Yes, will work on that

--
Igor Fabio Steinmacher, Ph.D.
Professor in Dept. of Computing at Universidade Tecnológica Federal do
Paraná

**Comment by igorsteinmacher** [comment]
Done,
Feel free to report any other issue :-)
