### ISSUE TITLE
Max-width columns

### ISSUE THREAD

**Issue by oscargus** [koppor/jabref#20]
When resizing the main window or resizing a column the width of all columns are affected. Since I started using JabRef on my high-res screen at work (on my laptop having too much space is not a problem...), I realized that it could be good if some columns had a max width as they typically don not benefit from further widening. One such simple example is the year column.

One way to implement it would be to add a checkbox to the column list in the preferences, where one can check that the number provided is a max (fixed?) width.

**Comment by koppor** [comment]
Related: In our [minutes](https://github.com/JabRef/jabref/wiki/Minutes), we have following line:

    must be implemented "vernünftig (matthias)" "Entry table -> fit table horizontally ....

This, however, has more todo with shrinking the table, not with enlarging.

@matthiasgeiger @simonharrer

**Comment by matthiasgeiger** [comment]
Good point. 

Other aspects for a "vernünftige" (=reasonable) implementation:
- "fit table horizontally" should be default --> always the full available screen should be used
  - pref option should be removed
- for each column a sensible min and/or max-width should be defined
- if and only if it is not possible to show all columns with their min-width horizontal scrollbars should appear

**Comment by simonharrer** [comment]
@matthiasgeiger does the current table support this now?

**Comment by matthiasgeiger** [comment]
no. as this is not so easy to achieve using Swing tables.

**Comment by simonharrer** [comment]
Then we should postpone this until we either have JavaFX or another GUI technology

**Comment by tobiasdiez** [comment]
Set on-hold or after migration to javafx?

**Comment by simonharrer** [comment]
I would set it on hold
