### ISSUE TITLE
Upgrade note field if containing url

### ISSUE THREAD

**Issue by koppor** [koppor/jabref#216]
note         = {\url{http://www.arcway.com/fileadmin/arcwaydateien/pdf/BPRE_Whitepaper.pdf}, visited 2007-09-15},

should become

    url = {http://www.arcway.com/fileadmin/arcwaydateien/pdf/BPRE_Whitepaper.pdf},
    note = {visited 2007-09-15},

The conversion should be named "Move URLs in note field to url field".

Should be placed as third the upper part of the cleanup dialog: https://docs.jabref.org/finding-sorting-and-cleaning-entries/cleanupentries

![image](https://user-images.githubusercontent.com/1366654/234899683-6d07a1cb-d474-45a0-b68e-6b54c25c2f39.png)

One can look at jabRef/jabref/src/main/java/org/jabref/logic/cleanup/EprintCleanup.java for an impression, how the implementation should like. There is also a test case: jjabRef/jabref/src/test/java/org/jabref/logic/cleanup/EprintCleanupTest.java

Please use `@ParameterizedTest` if possible (and doing more than one test, which is recommended).

**Comment by demetres12** [comment]
hello @koppor, can I get assigned?

**Comment by Alexandra-Stath** [comment]
Hello there, 
For our semester course @demetres12  and I are working as a team to fulfill our contribution on an open source software project. We are collaborating on this issue and I would like to be assigned as well for the necessities of our lesson.
Please assign me @koppor
Thank you in advance.

**Comment by Alexandra-Stath** [comment]
Hello there @koppor,
In order to keep you updated on my progress, I would like to inform you that within the next days I will open a draft pull request for this issue. Currently,  I am making the necessary adjustments to several classes in order to achieve the program's functionality. I need to add some parameterized tests, as well as, to verify the expected behavior of my code. 

Alexandra Stathopoulou

**Comment by Alexandra-Stath** [comment]
Hello @koppor,
I have almost finished with the requirements of the issue.
I have a question to ask you regarding the fuctionality of my code. 
In case there is already a url in the url field do I need to replace the existing one or just add the new one in the url field?
Please inform me,
Thank you in advance,
Alexandra Stathopoulou

**Comment by k3KAW8Pnf7mkmdSMPHz27** [comment]
@Alexandra-Stath 
As far as I know, you cannot/shouldn't add an additional URL to the URL field.

I'd propose,
1. changing the formulation of "Move URLs in note field to URL field" -> "Replace URL field with URL in note field" 
2. if there are multiple URLs in the note field, do nothing

I apologize in advance if someone else overrides this later, but from my point-of-view this makes the most sense.

**Comment by Alexandra-Stath** [comment]
>if there are multiple URLs in the note field, do nothing

Hello @k3KAW8Pnf7mkmdSMPHz27 
Shall we consider that case?
As you mentioned, we cannot store an additional URL to the url field, so why it would be possible two URLs to exist in the note field?

Thank you for the feedback.

**Comment by k3KAW8Pnf7mkmdSMPHz27** [comment]
> As you mentioned, we cannot store an additional URL to the url field, so why it would be possible two URLs to exist in the note field?

Because many fields in bibtex aren't well defined, the note field is one of them, e.g., https://www.bibtex.com/f/note-field/ essentially argues it is a field to store any relevant information that did not fit in any other field.
In a nutshell, you'll have to anticipate the user doing really weird things, in this case, I suppose, zero, one, or more than one URL in the note field are the relevant cases.

Additionally, If you search around a bit, you'll find posts like https://tex.stackexchange.com/a/57990 proposing it as an option for multiple URLs, which means someone is going to use it in that way for sure.

**Comment by Alexandra-Stath** [comment]
Thank you for the quick response. 
Wait till Monday, in case Oliver need to note/add something.

**Comment by koppor** [comment]
> @Alexandra-Stath As far as I know, you cannot/shouldn't add an additional URL to the URL field.

In case the URL field contains something, no action should be taken. -- JabRef should not destroy data.

>     1. changing the formulation of "Move URLs in note field to URL field" -> "Replace URL field with URL found in the note field"

In my opptionen, The whole operation is intended for mass cleanup - without requiring manual inspection after the action.

The text "Move ..." is also used by the other actions above. They are (hopefully) not destroying anything either... I opted for "Move" to indicate that the URL is disappearing from the note field after the action.

Thus, I ask for keeping the original text.

(And in the devcall or other sessions, we should discuss the whole dialog and the wording)

>     2. if there are multiple URLs in the note field, do nothing

With one exeption: In case the URL field is empty, move the first found url - and keep the second. -- This one is optional - if implemented, please also add test cases.

The test cases should cover

    note = {\url{http://example.org}}

    note = {\url{https://example.org}}

    note = {http://example.org}

Thus, the latex command `\url{}` should also be recognized - and removed at the move operation.

**Comment by demetres12** [comment]
@koppor

>In case the URL field contains something, no action should be taken. -- JabRef should not destroy data.

In case url field contains the same URL with the one in note, then wouldn't it be proper at least to remove the url from the note?

**Comment by koppor** [comment]
Agree! Thank you for thinking about that edge case! -- It is similar to the Move DOI behavior!

**Comment by Alexandra-Stath** [comment]
I have just opened the pull request regarding the issue.
@koppor @k3KAW8Pnf7mkmdSMPHz27

**Comment by koppor** [comment]
Discussion with @demetres12 - ´visited 2007-09-15` should be put in `urldate` ([org.jabref.model.entry.field.StandardField#URLDATE](https://github.com/koppor/jabref/blob/76c35f0afb6f9c700ee35a5475bbe9ff612fa75c/src/main/java/org/jabref/model/entry/field/StandardField.java#L121-L121).

Excerpt from biblatex manual:

![image](https://github.com/koppor/jabref/assets/1366654/d954c1c9-bc4d-4d6b-ab89-3dbe58e30036)

**Comment by demetres12** [comment]
So we are looking for a text like that: `visited / retrieved / accessed 2007-09-15` in both
URL and Note field to move it to urldate, or just in the Note field?

**Comment by koppor** [comment]
Interesting question. Handling `note` only would lead to include it at the new functionality URLCleanup. Making it available for both `url` and `note` field, it would be an additional CleanUpJob.

I like that JabRef tries to be precise about the things it does. There is no "magic cleanup" doing "something useful". This "visited" cleanup is something very special. I didn't encounter any bibtex file containging `, visited at 28. December 2022` or similar in the URL field. Did you? Did you do an extensive research on that?

Without any empirical data, I vote for handling the `note` field only and "magically" also updating "visited".

Please use [`org.jabref.model.entry.Date#parse(java.lang.String)`](https://github.com/JabRef/jabref/blob/9c5be3eab9b5d4029d8d37ffbe17c367b06cce0f/src/main/java/org/jabref/model/entry/Date.java#L107) for date parsing.

**Comment by demetres12** [comment]
> Handling note only would lead to include it at the new functionality URLCleanup

Agree. On the one hand JabRef needs to be precise and cover several unexpected cases a user may perform, but on the other hand this could lead to overkill (in our case of the cleanup activities)

> Did you? Did you do an extensive research on that?

Actually, I'm worried about the chance a user for unknown reasons include in the URL field info about date, but as you mentioned, there is no need for an additional check on URL field

**Comment by koppor** [comment]
> Actually, I'm worried about the chance a user for unknown reasons include in the URL field info about date, but as you mentioned, there is no need for an additional check on URL field.

You can add an integrity check.

UI: https://docs.jabref.org/finding-sorting-and-cleaning-entries/checkintegrity

While reading that code, I found [org.jabref.logic.integrity.UrlChecker](https://github.com/JabRef/jabref/blob/76c35f0afb6f9c700ee35a5475bbe9ff612fa75c/src/main/java/org/jabref/logic/integrity/UrlChecker.java#L8)

**Comment by demetres12** [comment]
@koppor 
When date is given from the user in the following format "January 15, 2021", should it be converted to "2021-01-15" before set in `urldate` field, or JabRef takes care of that conversion afterwards?

**Comment by koppor** [comment]
What is easier to implement? 😅 I think, keeping would be better 

Does JabRef have a date cleanup? Converting all dates? NormalizeDateFormat. Then a user can do that a separate step...
