### ISSUE TITLE
Cleanup should leve unknown paths untouched

### ISSUE THREAD

**Issue by koppor** [koppor/jabref#218]
When cleaning up

> file = {:/home/baumannfx/repos/Diss_GIT/sources/Rieder14.pdf:PDF},

gets

> file      = {:\\home\\baumannfx\\repos\\Diss_GIT\\sources\\Rieder14.pdf:PDF},

even if the file Rieder14.pdf does not exist on my machine.

This is wrong behavior. The entry should stay as is.

**Comment by Siedlerchr** [comment]
If the file/path doesn't exist it is not cleaned up.  Refs https://github.com/JabRef/jabref/pull/2415
