### ISSUE TITLE
Util...

### ISSUE THREAD

**Issue by oscargus** [koppor/jabref#22]
I thought I'd have a look at the util.Util file as it has met some criticism from the scientific community...

The plan is to check all the methods there, what they do, if they are used and so on. So here comes the first part:

 * ~~placeDialog: will be moved once the save position PR is finished and accepted~~ **Moved**
 * ~~parseField: **Never used**, except for the tests testing the function, should be used to convert to Bibkeeper(?) notation~~ **Removed**
 * ~~getPublicationDate: returns a formatted date (YYYY or YYYY-MM), used in XMPUtil~~ **Moved to BibtexEntry**
 *  checkLegalKey: checks if a Bibtex key is valid. Heavily used.
 * replaceSpecialCharacters: used by checkLegalKey (above) only, the only function that uses util.strings.UnicodeCharMap
 * ~~findDeliminatedWordsInField: Used in AutoGroupDialog only~~ **Moved**
 * ~~findAllWordsInField: Used in AutoGroupDialog only~~ **Moved**
 * ~~findAuthorLastNames: Used in AutoGroupDialog only~~ **Moved**
 * ~~sanitizeUrl: Used in JabRefDesktop only.  Could be used elsewhere though. Cleanup action for URLs?~~ **Moved to URLUtil**
 * parseMethodsCalls: Used (heavily) in LayoutEntry only **Move there?**
 * upgradePdfPsToFile (first): Used in FileLinksWarning only. Convenience method only calling function below **Use function below directly**
 * upgradePdfPsToFile (second): Only used as above and in CleanUpAction **Move to jabref.logic.cleanup?**
 * bindCloseDialogKeyToCancelAction: Used in a few dialogs to bind close key to cancel action in a single call **Move to gui.utils??**
 * updateTimeStampIsSet: Used in EntryEditor only. Returns the and of two boolean preferences. **Inline?**

**Comment by koppor** [comment]
parseField: Remove it. [Bibkeeper](http://bibkeeper.sourceforge.net/) merged with [JBibtexManager ](http://jbibtexmanager.sourceforge.net/) into JabRef. Therefore, functionality required for it is not necessary any more.

**Comment by oscargus** [comment]
PR #329 is a first step (including some other methods not mentioned above).

**Comment by oscargus** [comment]
With jabref/#1560 Util is finally history.
