### ISSUE TITLE
About dialog should always center on screen

### ISSUE THREAD

**Issue by koppor** [koppor/jabref#228]
After resetting the preferences and using a dev build from a few days ago, the about dialog is not centered on the screen:

![grafik](https://cloud.githubusercontent.com/assets/1366654/23019107/013d9324-f441-11e6-82f3-307f2c12ed9d.png)

I use 125% magnification:

![grafik](https://cloud.githubusercontent.com/assets/1366654/23019128/16c6a0a0-f441-11e6-9051-f13a219ecf3a.png)

**Comment by stefan-kolb** [comment]
For me it is always centered now. Even after moving the next invoction centers the window.
