### ISSUE TITLE
Speedup Build

### ISSUE THREAD

**Issue by koppor** [koppor/jabref#230]
There was a travis speedup made at https://github.com/JabRef/jabref/pull/2544

The Gradle Bulid scren results (https://gradle.com/s/mi2scw7lfi7vy) show following:

![grabbed_20170216-221732](https://cloud.githubusercontent.com/assets/1366654/23041681/fe6fa740-f495-11e6-8f5e-8529a3d814a8.png)

Maybe we should split up some tests. Maybe the citationstyle testss? See

![grabbed_20170216-222029](https://cloud.githubusercontent.com/assets/1366654/23041727/2be8eccc-f496-11e6-9f1e-2fd710fb3a55.png)

**Comment by stefan-kolb** [comment]
We discussed that it is fast enough for now.
