### ISSUE TITLE
Mr. DLib sometimes does not recommend anything

### ISSUE THREAD

**Issue by stefanfeyer** [koppor/jabref#231]
In the build, a selected item produces a "Error while Fetching from Mr. DLib".
The same item works when JabRef is started from Eclipse.
This is an example BibTex file where we (2 systems in Dublin and in Tokyo) observed it.

@inproceedings{Hornecker:2006:GGT:1124772.1124838,
address = {New York, NY, USA},
author = {Hornecker, Eva and Buur, Jacob},
booktitle = {Proceedings of the SIGCHI Conference on Human Factors in Computing Systems},
doi = {10.1145/1124772.1124838},
isbn = {1-59593-372-7},
keywords = {CSCW,analysis,collaboration,design,framework,social interaction,tangible interaction,tangible interface},
pages = {437--446},
publisher = {ACM},
series = {CHI '06},
title = {{Getting a Grip on Tangible Interaction: A Framework on Physical Space and Social Interaction}},
url = {http://doi.acm.org/10.1145/1124772.1124838},
year = {2006}
}

**Comment by koppor** [comment]
Mr. DLib should write more logs if it does something.

Currently, just nothing happens and there is no information on the "Error Console".

![mrdlib](https://cloud.githubusercontent.com/assets/1366654/23591237/979ac8fa-01ed-11e7-91d5-bffd7a95ba67.gif)

**Comment by koppor** [comment]
I found the issue. It seems, you did not test locally with latest master, but with your old customized version. This did not include our latest fix for Mr DLib (https://github.com/JabRef/jabref/pull/2567). Thus, you could not reproduce the issue locally.

I used the latest master and debugged into the methods.

Please try the latest build available at http://builds.jabref.org/fixmrdlib/. Now, everything should work fine.
