### ISSUE TITLE
New MetaData serialization

### ISSUE THREAD

**Issue by stefan-kolb** [koppor/jabref#232]
Ideas: 
- Reuse BibTeX parser logic as far as possible
- Drop custom String parsing logic
- Make it obvious which data is related to Jabref
- One Bibentry as configuration object, e.g., saveactions -> SaveAction.java

old:

    @Comment{jabref-meta: databaseType:bibtex;}

new:

```
@JabRef{metadata,
  databasetype = {bibtex}
}
```

old:

```
@Comment{jabref-meta: saveActions:enabled;
date[normalize_date]
pages[normalize_page_numbers]
month[normalize_month]
;}
```

new:

```
@JabRef{saveActions,
  state = {enabled},
  date = {normalize_date, action2}
  pages = {normalize_page_numbers}
  month = {normalize_month}
}
```

**Comment by tobiasdiez** [comment]
I really like the idea! Maybe the `JabRef` type might lead to problems but otherwise a very readable and understandable format!

**Comment by koppor** [comment]
Refs https://github.com/JabRef/help.jabref.org/issues/227

**Comment by koppor** [comment]
Refined issue at https://github.com/JabRef/jabref/issues/10371.
