### ISSUE TITLE
title_case/capitalize modifiers do not work on all fields

### ISSUE THREAD

**Issue by koppor** [koppor/jabref#237]
Help https://help.jabref.org/en/BibtexKeyPatterns shows `camel`, but this should be a modifier. Example: `[title:title_case]`

However, it does not work.

## Actions

- [x] Cleanup doc 
- [x] Cleanup code.

**Comment by RolfStarre** [comment]
The example that you give also isn't mentioned in the modifiers on https://help.jabref.org/en/BibtexKeyPatterns

**Comment by Siedlerchr** [comment]
@RolfStarre  Hi, we discovered a unit test from the old PR of @oscargus  who once implemented it with the name title_case (which in fact is camel case, but it doesn't work on all fields, (especially it does not work on shorttitle)
And furthermore, we got to the conclusion that there was misunderstanding when writing the documentation for that implementation.


https://github.com/JabRef/jabref/pull/1894

**Comment by RolfStarre** [comment]
@Siedlerchr Thanks for the clarification 👍 

I'll try to find some time to help improve it this week, by adding some tests and trying to fix the issues with the modifiers.

**Comment by koppor** [comment]
@RolfStarre May I hope that you still know which documentation you wanted to update? Maybe the PR could also go forward. I outlined an idea at https://github.com/JabRef/jabref/pull/2663#issuecomment-304700694.

**Comment by koppor** [comment]
The documentation probably is https://docs.jabref.org/setup/citationkeypatterns
