### ISSUE TITLE
Integrate "References in the article" functionality

### ISSUE THREAD

**Issue by koppor** [koppor/jabref#240]
Idea from: http://tex.stackexchange.com/q/364023/9075

NASA ADS allows for fetching cited entries from a paper via http://adsabs.harvard.edu/cgi-bin/bib_query?arXiv:1704.00684. We could integrate this service as fetcher.

Extended idea: Evaluate other alternatives and implement parsing of the PDF or similar functionality.

This somehow refs https://github.com/koppor/jabref/issues/95, because PRRV also extracts references, but in a very easy way. It also relies that the referenced papers are in the paper database.

**Comment by tobiasdiez** [comment]
It would be nice if the extracted references are automatically compared to the current database (e.g. I can see which referenced articles are already contained in my database).

CERMINE can also extract bibliographic information about the cited papers. 

On the other end of the spectrum, there are also websites that provide information about where the given article is cited in. For example, [MathSciNet](http://www.ams.org/mathscinet/search/publications.html?bdlall=Retrieve+First+50&reqargs=amp%253D%2526loc%253Drefcit%2526r%253D1%2526refcit%253D1641660%2526vfpref%253Dbibtex&batch_title=Selected+Matches+for%3A+Citations+of+1641660&fmt=bibtex). This may also worth a new fetcher.

**Comment by koppor** [comment]
Duplicate of https://github.com/JabRef/jabref/issues/6187
