### ISSUE TITLE
Required aliassed fields should not indicate a warning

### ISSUE THREAD

**Issue by koppor** [koppor/jabref#246]
Biblatex mode. We show both journal and journal title.

Even if "journal" is filled, journal title gets a warning:

![grafik](https://user-images.githubusercontent.com/1366654/29471877-f0248c2c-8451-11e7-9e27-484bfe7d7f93.png)

**Comment by tobiasdiez** [comment]
The error message does not concern the journaltitile field but probably the author. The issue that warnings are not correctly placed is already tracked in the main rep (and was the reason why this feature was temporarily disabled).
