### ISSUE TITLE
Link is not relativized any more

### ISSUE THREAD

**Issue by koppor** [koppor/jabref#247]
Setting:

empy main directory:

![grafik](https://user-images.githubusercontent.com/1366654/29472080-ccdecf88-8452-11e7-8d7f-298ce76ebfdb.png)

But library directory:

![grafik](https://user-images.githubusercontent.com/1366654/29472007-870eebdc-8452-11e7-85b0-e8593fad7912.png)

1. Attach file `C:\Users\koppor\BTSync\lit\CloudComputing\Barnawi_2015 - Runtime self-monitoring approach of business process compliance in cloud environments.pdf`
2. Expect: `CloudComputing\Barnawi_2015 - Runtime self-monitoring approach of business process compliance in cloud environments.pdf` as entry at File

Real result:

![grafik](https://user-images.githubusercontent.com/1366654/29472040-a960fb8a-8452-11e7-93c3-fa6c0140858b.png)

**Comment by Siedlerchr** [comment]
In library properties you can enter relative directories and the file will the relativized successfully.

So just enter `CloudComputing`:

![grafik](https://user-images.githubusercontent.com/320228/29866297-4e17aba0-8d78-11e7-9b2a-fcfb620234a5.png)

![grafik](https://user-images.githubusercontent.com/320228/29866312-593ad0e8-8d78-11e7-8c52-0d3a2e9e9f98.png)

**Comment by koppor** [comment]
I want to set an absolute directory at the bib file. This does not work. This should work independently of global settings.

**Comment by koppor** [comment]
Double checked. Works now. Strange.
