### ISSUE TITLE
Autocomplete in Search Bar is strange

### ISSUE THREAD

**Issue by koppor** [koppor/jabref#253]
## Before pressing enter

![grafik](https://user-images.githubusercontent.com/1366654/30001800-21c26864-9099-11e7-9c7a-9a530490891e.png)

## After pressing enter

![grafik](https://user-images.githubusercontent.com/1366654/30001801-2b3773bc-9099-11e7-9bb6-85917ef57d99.png)

Why are there no entries marked?

**Comment by Siedlerchr** [comment]
I found out that this only works if you remove the last dot of the author, then the right entry is selected.
So in your case delete the last dot after the `Author R.`
![grafik](https://user-images.githubusercontent.com/320228/30002682-36e028e6-90b0-11e7-8022-c1d74f7c4d4b.png)

Without dot 
![grafik](https://user-images.githubusercontent.com/320228/30002684-3bc1b79e-90b0-11e7-9be4-fbf0c4619347.png)

**Comment by lynyus** [comment]
Fixed in https://github.com/JabRef/jabref/pull/3240
