### ISSUE TITLE
Paste of Google URL

### ISSUE THREAD

**Issue by koppor** [koppor/jabref#254]
We had a functionality to cleanup Google URLs. This should be transparent for the user.

![grafik](https://user-images.githubusercontent.com/1366654/30013825-11790804-9149-11e7-9790-f8956e105875.png)

**Comment by 1161140207** [comment]
Hi, @koppor . I am a newcomer to this project and find this issue may be a good one to try. I notice that someone had tried to contribute to it but somehow gave it up. 
https://github.com/JabRef/jabref/pull/3394 
Is this issue still need to be done now?

**Comment by koppor** [comment]
https://github.com/JabRef/jabref/pull/3394 is closed with unmerged commits. So, the functionality is not in JabRef.

You can do following: Create a new branch at your side, copy and paste the changes from https://github.com/JabRef/jabref/pull/3394/files, address the comments from https://github.com/JabRef/jabref/pull/3394 (e.g., "Avoid the non null annotation and use Objects.requireNonNulll", "Description should be localized, too") and create a new pull request.

Reference this issue from the pull request.

We really look forward to get this into JabRef.

**Comment by tobiasdiez** [comment]
This is now implemented in the latest development version thanks to @1161140207. Could you please check the build from http://builds.jabref.org/master/. Thanks! Please remember to make a backup of your library before trying-out this version.
