### ISSUE TITLE
Files appear twice

### ISSUE THREAD

**Issue by koppor** [koppor/jabref#259]
![grafik](https://user-images.githubusercontent.com/1366654/30095101-a867ecd4-92d0-11e7-9b86-93e6f0361866.png)

![grafik](https://user-images.githubusercontent.com/1366654/30095109-b60a51e2-92d0-11e7-8db4-f7f95377261f.png)

@Siedlerchr said it is about auto linking. Could you explain if this a new feature? I thought, auto linking is only done if (1) I push the button for auto linking or (2) If I open the file? Why is it done on opening the entry editor and then wrong?

**Comment by Siedlerchr** [comment]
I can not reproduce it: The autolink is done when opening the entry editor for the entry (setting: "When opening file link, search for matching fielink if none defined

**Comment by koppor** [comment]
A reset of the preferences solved the issue.
