### ISSUE TITLE
Refactor OpenDatabaseAction class

### ISSUE THREAD

**Issue by tobiasdiez** [koppor/jabref#26]
The loadDatabase() method shouuld be moved to another place. The OpenDatabaseAction class contains quite a lot of gui stuff while this method is purely logic.

See [PR 361](https://github.com/JabRef/jabref/pull/361) for details.

**Comment by simonharrer** [comment]
:+1:

**Comment by koppor** [comment]
Duplicate of https://github.com/JabRef/jabref/issues/8298
