### ISSUE TITLE
Fix ANTLR error output

### ISSUE THREAD

**Issue by koppor** [koppor/jabref#266]
```
ANTLR Tool version 4.5.3 used for code generation does not match the current runtime version 4.7
```

In a freshly checkout JabRef when using the search.

**Comment by Siedlerchr** [comment]
We should also maybe move the BST grammar to antlr4.
I actually have no idea what the purpose of the BST grammar is

**Comment by koppor** [comment]
We have the bibtex vm, which can interpret bst files. One has to work on
that. Will be a cool feature. Alternative to CSL!

Am 16.12.2017 18:59 schrieb "Christoph" <notifications@github.com>:

**Comment by koppor** [comment]
Meanwhile, this does not appear anymore.
