### ISSUE TITLE
Switch from VersionEye to another solution

### ISSUE THREAD

**Issue by koppor** [koppor/jabref#267]
VersionEye is shutting down: https://blog.versioneye.com/2017/10/19/versioneye-sunset-process/

- Find another solution (overview at https://alternativeto.net/software/versioneye/)
- Implement it

https://www.whitesourcesoftware.com/contact-us-open-source/ might also be interesting

https://libraries.io/ looks most promising

**Comment by koppor** [comment]
Let's see, what happens:

![grafik](https://user-images.githubusercontent.com/1366654/31807067-28e5b16c-b56c-11e7-8752-8597a460280c.png)

**Comment by Siedlerchr** [comment]
https://requires.io/ also has a free plan for public repos

**Comment by stefan-kolb** [comment]
We use dependabot now.
