### ISSUE TITLE
On disk changes: Revert selection

### ISSUE THREAD

**Issue by koppor** [koppor/jabref#280]
![grafik](https://user-images.githubusercontent.com/1366654/33709139-bc75ef32-db3c-11e7-88fb-da65386fd2f7.png)

After clicking "Review changes", following dialog pops up:

![grafik](https://user-images.githubusercontent.com/1366654/33709071-860262d2-db3c-11e7-8745-75b1aa48d3c8.png)

Wie man die "Auswahl umkehren" kann, wenn man gefragt wird, was JabRef
mit all den on-disk veraenderten Eintraegen machen soll: wenn man alle
oder fast alle akzeptieren will, muss man, soweit ich sehe, jeden
einzelnen anklicken. Ein "select all" button waere of sehr bequem.

**Comment by koppor** [comment]
Complex follow-up: https://github.com/koppor/jabref/issues/273

**Comment by Siedlerchr** [comment]
This has been implemented as part of https://github.com/JabRef/jabref/pull/5803
You now can click on the arrows to select all.
