### ISSUE TITLE
New cleanup for em dash

### ISSUE THREAD

**Issue by koppor** [koppor/jabref#286]
IEEE renders an EM dash as follows:

     {\&}{\#}x2014$\mathsemicolon$

Example:

  title = {Towards situation-aware adaptive workflows: {SitOPT} {\&}{\#}x2014$\mathsemicolon$ A general purpose situation-aware workflow management system},

Paper:

![grafik](https://user-images.githubusercontent.com/1366654/35505109-55ebc76e-04e5-11e8-8c1d-7306a5f47f64.png)

http://ieeexplore.ieee.org/document/7133989/

There should be a cleanup during fetching.

**Comment by koppor** [comment]
Help page for working on fetchers: https://devdocs.jabref.org/advanced-reading/fetchers

**Comment by koppor** [comment]
1. Create test case in `org.jabref.logic.importer.fetcher.IEEETest`
2. Check what is returned for `10.1109/PERCOMW.2015.7133989`
3. Add cleanup class - and integrate it into `IEEE` fetcher class.

**Comment by aryanVanaik** [comment]
Hi there, could I be assigned to this issue for a university project

**Comment by aryanVanaik** [comment]
Hi, I have solved this issue would I be able to make a PR

**Comment by koppor** [comment]
@aryanVanaik Just go ahead and file a PR to https://github.com/JabRef/jabref/. - In the open source world, one (should) just be able to submit PRs :). Looking foward. - Please also link this issue with the full URL from the pull request.

**Comment by aryanVanaik** [comment]
HI @koppor I have made a pull request specifically #662 please let me know if there are any issues :)

**Comment by koppor** [comment]
@aryanVanaik I commented at the PR, let's continue the discussion there.
