### ISSUE TITLE
Chaning entry type is not possible any more

### ISSUE THREAD

**Issue by koppor** [koppor/jabref#289]
![grafik](https://user-images.githubusercontent.com/1366654/35512780-3c13a9b2-0501-11e8-9b72-8e493b604848.png)

Right click on Conference, select "InProceedings":

![grafik](https://user-images.githubusercontent.com/1366654/35512794-457a8b7e-0501-11e8-9035-b77d6c52650a.png)

Nothing happens.

BUT the Type should have changed into "InProceedings".

**Comment by koppor** [comment]
Oh, JabRef changes the type, but neither updates the type indicator of the entry editor nor the bibtex source.

**Comment by lenhard** [comment]
Fixed by https://github.com/JabRef/jabref/pull/3714
