### ISSUE TITLE
Include test cases for other types

### ISSUE THREAD

**Issue by koppor** [koppor/jabref#29]
[othertype.bib](https://github.com/JabRef/jabref/blob/1a9b6e7cd0b4d75782057e029018c4981a7b7415/src/test/resources/testbib/othertype.bib) and [reallyunknowntype.bib](https://github.com/JabRef/jabref/blob/1a9b6e7cd0b4d75782057e029018c4981a7b7415/src/test/resources/testbib/reallyunknowntype.bib). When reading and writing the file, the output should be equal to the original file. Especially, no type should have been changed.

**Comment by tschechlovdev** [comment]
I've added the test cases for other and reallyunknowntype. So can this be closed?

**Comment by koppor** [comment]
Yes, there are test cases (https://github.com/JabRef/jabref/pull/2152/files). No, the test case do not read and write these files. With the feature that an entry is only rewritten if it changed, these bib files should not change too. However, I'd like to be 100% sure.

The intention of the issue is that there might be impact of using a whole bibdatabase instead of a single bibentry object.

**Comment by tobiasdiez** [comment]
The tests check that the correct type gets parsed and ensure that the correct string is written. So there is nothing which can go wrong in a roundtrip, except if somebody changes the BibEntry in between. (Actually, this is the nice thing about unit-testing the parser and writer: you can be sure that the roundtrip works too, but if something goes wrong you know exactly where the error is).

Moreover, there exists 

So I also vote for closing this issue.

**Comment by koppor** [comment]
I now understood the comments. The BibEntries are read and then compared. Thus, the discussion on writing misses the point.
