### ISSUE TITLE
Normalize Author Names should be able to treat multiple ,

### ISSUE THREAD

**Issue by koppor** [koppor/jabref#294]
Florian Maier, Andreas Wohlfrom, Falko Koetter, Sabrina Merkel-Malkowskiy and Daniel Zech

should be normalized to

   Maier, Florian and Wohlfrom, Andreas and Koetter, Falko and Merkel-Malkowskiy, Sabrina and Zech, Daniel

Currently, it is normalized to

    Florian Maier, Andreas Wohlfrom, Falko Koetter Sabrina Merkel-Malkowskiy and Zech, Daniel

I know, we had huge discussions about that. I need to dig into that and understand why THREE commas and ONE AND are not interpreted as case where the first names are ill formatted.

Source of the names: copy and paste of a paper

![grafik](https://user-images.githubusercontent.com/1366654/35561547-f0e37f70-05b0-11e8-9417-e986710b5f70.png)

Source of the PDF: https://www.thinkmind.org/index.php?view=article&articleid=energy_2016_2_30_30051

**Comment by tobiasdiez** [comment]
I think the problem is again the junior part:
`LastName, Jr., FirstName and SecondLastName, SecondFirstName` is correct but has 3 commas and one and.

**Comment by koppor** [comment]
I would guess only 1% of the papers at max have this in them. In my whole career, I never put them in my bib file.

Reading http://www.chicagomanualofstyle.org/qanda/data/faq/topics/Jr.Sr.III/faq0002.html and https://en.wikipedia.org/wiki/Suffix_(name) I would guess that the junior part is the "suffix (name)" and that this (nearly) never takes any space in it.

Maybe, a preference could help:

    - [ ] at normalization, try to keep junior parts of the name

With default: off 😇

**Comment by koppor** [comment]
Test cases:

Lastname1, Jr1, Firstname1 and Lastname2, Jr2, Firstname2

(See tex.stackexchange.com/q/206760/9075)

**Comment by koppor** [comment]
Frozen, because only required if we parse names manually.
