### ISSUE TITLE
Improve context menu

### ISSUE THREAD

**Issue by koppor** [koppor/jabref#298]
![grafik](https://user-images.githubusercontent.com/1366654/35571935-bb96a022-05d3-11e8-9a60-591a838871a0.png)

**Comment by tobiasdiez** [comment]
I think, it is actually quicker if you just create a PR with the fix instead of a nice screenshot with text 😈

**Comment by lenhard** [comment]
Fixed by https://github.com/JabRef/jabref/pull/3726
