### ISSUE TITLE
DOI: encoded URLs should be supported

### ISSUE THREAD

**Issue by koppor** [koppor/jabref#3]
When building a DOI, strings like `https://dx.doi.org/10.2307%2F1990888` should also be accepted

**Comment by stefan-kolb** [comment]
I think it is not possible to identify which parts of the DOI are escaped and which are not. Where is this a problem?

**Comment by koppor** [comment]
The DOI specifcation talks about encoding at https://www.doi.org/doi_handbook/2_Numbering.html#htmlencoding. I don't remember, where I hit the issue, but I never saw DOIs containing a real `%` (and not used for encoding) in the wild... Possibly, whenever the DOI is an URL (`http...`), decoding should be applied.
