### ISSUE TITLE
GVK and dblp fetchers crash if patternpedia is used in the search term

### ISSUE THREAD

**Issue by koppor** [koppor/jabref#306]
1. Active GVK Fetcher (or DBLP fetcher)
2. Search for `fehling patternpedia` or just `patternpedia`
3. The popup appears and immediatly closes

![grafik](https://user-images.githubusercontent.com/1366654/36257075-c5ebf71e-1255-11e8-8f1d-08319380e504.png)

**Comment by koppor** [comment]
1. Create test cases in the respective fetcher test (`org.jabref.logic.importer.fetcher.GvkParserTest`, `org.jabref.logic.importer.fetcher.DBLPFetcherTest`)
2. Check what the search returns
3. Think what may be the reason

**Comment by lachiri-ilias** [comment]
hey, is this still an issue to be fixed ?

**Comment by koppor** [comment]
@lachiri-ilias Thank you for checking. I tried today, and it works.
