### ISSUE TITLE
Centering of number column

### ISSUE THREAD

**Issue by koppor** [koppor/jabref#31]
The number column is sometimes not centered. It should always be left aligned.

![grabbed_20151120-171101](https://cloud.githubusercontent.com/assets/1366654/11304739/afa658c2-8fa9-11e5-8f99-6f9812406a4c.png)

**Comment by bartsch-dev** [comment]
When searching the number of the matched entries gets centered (the grayed-out are left aligned).
Isn't this by design?

**Comment by tobiasdiez** [comment]
Probably it is "by design" but by a rather strange design 😄 I think it doesn't make sense to change the alignment based on hit vs no-hit. Always left aligned makes sense.

**Comment by bartsch-dev** [comment]
Currently when no search is active the numbers are centered.
When searching and entries get grayed out those numbers are left aligned.
Should it be always centered or always left aligned?
