### ISSUE TITLE
Integrate anystyle

### ISSUE THREAD

**Issue by koppor** [koppor/jabref#315]
https://anystyle.io/

This can replace FreeCite or just be an additional button.
See https://help.jabref.org/en/NewEntryFromPlainText for the current UX.

**Comment by Siedlerchr** [comment]
Refs https://github.com/JabRef/jabref/issues/561

**Comment by koppor** [comment]
This is especially important, because FreeCite was shut down recently:

https://library.brown.edu/libweb/freecite_notice.php

**Comment by koppor** [comment]
Online web service currently shut down: - https://github.com/inukshuk/anystyle#web-application-and-web-service

![grafik](https://user-images.githubusercontent.com/1366654/68479536-d990fe80-0232-11ea-9805-5f709b995996.png)

**Comment by koppor** [comment]
Follow up at https://github.com/JabRef/jabref/pull/5614. Will be GROBID instead of anystyle

**Comment by koppor** [comment]
Anystyle is back:

<blockquote class="twitter-tweet"><p lang="en" dir="ltr">I&#39;m happy to announce that <a href="https://t.co/YufeDlCUHj">https://t.co/YufeDlCUHj</a> is back online. It has been updated to use the latest version of the parser and the we app itself is now also open source!</p>&mdash; C. Auguste Dupin (@1nukshuk) <a href="https://twitter.com/1nukshuk/status/1209118529183768577?ref_src=twsrc%5Etfw">December 23, 2019</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
