### ISSUE TITLE
Support FJOURNAL field

### ISSUE THREAD

**Issue by koppor** [koppor/jabref#321]
Idea from https://blogs.ams.org/beyondreviews/2015/07/11/references-and-citations/

`FJOURNAL` stores the full journal name for internal reference.

Example:

```bibtex
@article {MR997568,
    AUTHOR = {Mumford, David and Shah, Jayant},
     TITLE = {Optimal approximations by piecewise smooth functions and
              associated variational problems},
   JOURNAL = {Comm. Pure Appl. Math.},
  FJOURNAL = {Communications on Pure and Applied Mathematics},
    VOLUME = {42},
      YEAR = {1989},
    NUMBER = {5},
     PAGES = {577--685},
      ISSN = {0010-3640},
     CODEN = {CPAMA},
   MRCLASS = {49F20 (41A30 92A27)},
  MRNUMBER = {997568 (90g:49033)},
MRREVIEWER = {Constantin Udri{\c{s}}te},
       DOI = {10.1002/cpa.3160420503},
       URL = {http://dx.doi.org/10.1002/cpa.3160420503},
}
```

**Comment by koppor** [comment]
When abbreviating, the full abbreviation should be stored in `fjournal`. When expanding, the full name should be moved from `fjournal` to `journal`.

**Comment by xianghao-wang** [comment]
Hello, could you assign this issue to me?

**Comment by koppor** [comment]
Think of following cases:

- `journal` field exists, `fjournal` does not - and user abbreviates
- `journal` field exists, `fjournal` does exist - and user unabbreviates (IMHO the content of `fjournal` should be written into `journal` and then the field `fjournal` should be removed)

Please do test-driven development and craft test cases first.

**Comment by Siedlerchr** [comment]
@koppor  I think it does not make sense to introduce the field if it does not exist yet. This might confuse users that are not aware or don't use this ams stuff
