### ISSUE TITLE
XMP: Import of PDF with XMP data does not show XMP

### ISSUE THREAD

**Issue by koppor** [koppor/jabref#338]
Test PDF: https://github.com/JabRef/jabref/blob/feature/xmp-provement/src/test/resources/pdfs/KoppAZ-MADR-ZEUS-2018/KoppAZ-MADR-ZEUS-2018.pdf

Drag'n'drop on Maintable results in following dialog:

![grafik](https://user-images.githubusercontent.com/1366654/38688287-f823e986-3e78-11e8-951f-6a1d133529b5.png)

In case XMP data is found, it reads as follows:

![grafik](https://user-images.githubusercontent.com/1366654/38688305-061ad5b8-3e79-11e8-9c84-bd95aadcd911.png)

**Comment by johannes-manner** [comment]
The problem is, that the xmp metadata section is faulty:
![image](https://user-images.githubusercontent.com/30231151/38732995-9200fcfe-3f20-11e8-911b-88c2274b84df.png)

**Comment by koppor** [comment]
I sent it through the validator - and it is OK:

![grafik](https://user-images.githubusercontent.com/1366654/38739993-ba48816c-3f36-11e8-94b8-dea795e9ec83.png)

OK, I See. Can JabRef at the XMP export remove 

    <?xpacket begin="﻿" id="W5M0MpCehiHzreSzNTczkc9d"?>

and

    <?xpacket end="w"?>

?

The result is now:

```
@inproceedings{KoppEtAl-MADR2018,
  author = {Oliver Kopp and Anita Armbruster and Olaf Zimmermann},
  booktitle = {Proceedings of the 10th Central European Workshop on Services and their Composition ({ZEUS} 2018)},
  keywords = {ADR, MADR, architecture decision records, architectural decision records, Nygard},
  month = {#jan#},
  pages = {55--62},
  publisher = {CEUR-WS.org},
  series = {{CEUR} Workshop Proceedings},
  title = {Markdown Architectural Decision Records: Format and Tool Support},
  url = {https://adr.github.io/madr/},
  volume = {2072},
  year = {2018}
}
```

So, it basically looks great, but the month should be displayed as `month = jan`. I do not know where this comes from.

**Comment by johannes-manner** [comment]
Is it necessary to remove the duplicated begin-tags?

If I write the xmp data with JabRef, there is no duplicated entries. Otherwise I have to modify the InputStream before the dom xmp parsing happens, because I have no control over the org.apache.xmpbox.xml.DomXmpParser.DomXmpParser.

A workaround would be to capture the exception and return a empty bib entry with a comment, that the xmp is not valid or another error message?

**Comment by johannes-manner** [comment]
Okay, now I understand the problem. The export xmp should not contain the begin-tag, as mentioned in the xmpincl package. 

I reproduced your problem now. Normally, we don't need this begin-xml-processing instruction!

**Comment by koppor** [comment]
Fixed by https://github.com/JabRef/jabref/pull/3964
