### ISSUE TITLE
Evaluate flatpack

### ISSUE THREAD

**Issue by koppor** [koppor/jabref#342]
https://flatpak.org/

Instead of snapcraft

Background: https://www.pro-linux.de/news/1/27216/linux-mint-wettert-gegen-canonicals-snap.html

**Comment by Siedlerchr** [comment]
WIP now : https://github.com/JabRef/jabref/pull/5409

**Comment by koppor** [comment]
Refs https://github.com/flathub/org.freedesktop.Sdk.Extension.openjdk/issues/1
