### ISSUE TITLE
Feature: Short references: Include shortdoi service

### ISSUE THREAD

**Issue by koppor** [koppor/jabref#343]
http://shortdoi.org/

1. User clicks feature "short reference".
2. JabRef shortens all DOI fields using http://shortdoi.org/

**Comment by dawidowoc** [comment]
Hello. I'd like to work on this issue. Can I take it? :)

**Comment by koppor** [comment]
Sure!

**Comment by dawidowoc** [comment]
I'm thinking about how exactly we want this feature to look like. I think that we can add a new option in the menu bar in **Tools** which will be called **Shorten DOIs**. Clicking this option will shorten all DOIs in current library's entries. Now I've got a question about it. Should we also have feature of shortening DOI in each entry separately? One more thing. Do we want to have **Unshorten DOIs** feature?

**Comment by koppor** [comment]
We have the CleanUp feature. Please read into https://github.com/JabRef/jabref/blob/master/src/main/java/org/jabref/logic/cleanup/DoiCleanup.java.

https://help.jabref.org/en/CleanupEntries

That feature is a field formatter.

In a second step, we could think of some more accessible UI. I would put a toggle button next to the DOI field "shortened" "long version".

**Comment by tobiasdiez** [comment]
Thanks to @dawidowoc the short doi is now implemented as a formatter. 

The feature should also be accessible via the right-click menu. However, this is currently blocked by https://github.com/JabRef/jabref/issues/5254.

**Comment by koppor** [comment]
Thus, I close the issue as the PR is merged.
