### ISSUE TITLE
Integrate check-bib-for-predatory

### ISSUE THREAD

**Issue by koppor** [koppor/jabref#348]
https://github.com/CfKu/check-bib-for-predatory

See also https://discourse.jabref.org/t/double-check-the-bibliography-for-predatory-publishers-and-journals/1738

**Comment by milescajus** [comment]
Hi, just to let you know in case you weren't notified, the draft PR for this issue is now ready for review :) thanks!

**Comment by u7485624** [comment]
Hello, I'm a beginner programmer and am interested in working in this issue.

I have read the onboarding pages accordingly and would like a shot at creating an implementation.

**Comment by xuanan20020** [comment]
Hi, koppor, I hope you are doing well. I have noticed that milescajus is no longer interested in this issue. May I take over as an assignee. Thank you :D!

**Comment by koppor** [comment]
@xuanan20020 Sure thing. You now even have a "template" for MV file generation at [/src/main/java/org/jabref/cli/JournalListMvGenerator.java#L19](https://github.com/JabRef/jabref/blob/d55b7ff7c84aee73369faed6e93d539e8bc403df/src/main/java/org/jabref/cli/JournalListMvGenerator.java#L19), which was introduced at https://github.com/JabRef/jabref/pull/10298. With the previous try and that PR, you should have a good start!

**Comment by reox** [comment]
I saw this feature in 5.12 and tested it. However, I fear there are many false positives. For example, if the Publisher is "Springer", "Wiley", "CRC Press" or "Nature Publishing Group", the article/book gets flagged. Sure, you can have some opinions about these publishers but I hope that these are still credible :D 
It is also funny that it shows "Science" or "Bone" as predatory journals - which I hope are not...

It would certainly help to show some reasoning behind the flagging, i.e., "shows up in List xyz"

**Comment by fofusa** [comment]
Hello,
My experience is the same than reox.
I just tried this feature on my own database and there are way too many false positives including Nature, Science or journal of the OSA (Optical Society of America) like Optics Letters.
These are highly respected journals that most scientists in my field would not consider predatory.
I think there is something wrong with the list used for flagging.

**Comment by Siedlerchr** [comment]
Maybe we also should limit it to full titles as we currently do also similarity check for the title ?

**Comment by SReich-EMI** [comment]
I just now found that predatory journal check. My experience is also very bad. There are much too much false positive. With this, this check is not usefull in my point of view. I even checked some of the flase positive, but did not find them in the list from [https://github.com/stop-predatory-journals/stop-predatory-journals.github.io/blob/master/_data/journals.csv](https://github.com/stop-predatory-journals/stop-predatory-journals.github.io/blob/master/_data/journals.csv).
My suggestion is to first remove the tool for the next version and only implement it again, when it is running much better.
I don't know about the porgramming of JabRef. Therefore, I can not help in programming, sorry. 
If the tool is based on this stop-predatory-journals list, maybe this has to be extended to include the publisher and the basic journal DOI to be checked in this tool.

**Comment by Siedlerchr** [comment]
@koppor  That feature was removed in 5.13 again

**Comment by koppor** [comment]
> @koppor  That feature was removed in 5.13 again

I still wonder which version @SReich-EMI uses and how this old version happens to be in his machine...
