### ISSUE TITLE
Support biblatex's format of nameparts

### ISSUE THREAD

**Issue by koppor** [koppor/jabref#356]
Biblatex offers special markes in authors fields... Mix and match possible (meaning: in one field first name in bibtex format, lastname in biblatex special format).

Russian and Chinese usage

We should support that too to increase usage in that areas.

**Comment by Gelma1** [comment]
[logs_30712.zip](https://github.com/koppor/jabref/files/8508941/logs_30712.zip)

**Comment by koppor** [comment]
Duplicate of https://github.com/JabRef/jabref/issues/4558
