### ISSUE TITLE
cancelled/canceled

### ISSUE THREAD

**Issue by oscargus** [koppor/jabref#36]
The spelling of cancelled/canceled is inconsistent. This holds in real life as well, with canceled being British and cancelled everything else (American, Australian, ...). Any policy on this in general? Maybe should be stated in Code Howtos?

**Comment by koppor** [comment]
According to [the Grammarist](http://grammarist.com/spelling/cancel/), it's the other way round: AE: "canceled" and BE: "cancelled". In our research, we have the same issue with "modeling" vs. "modelling". Although we stick to AE, we write "modelling". I currently lean towards the double-l and would add that to the [Code Howtos](https://github.com/JabRef/jabref/wiki/Code-Howtos).

**Comment by oscargus** [comment]
OK! I read it late last night... I also think double-l looks better (that's why I spotted it, 63 single-l instances I think). Then there's optimization/optimisation etc. OK, so AE except for words which are apparently ugly in AE. :-)

**Comment by koppor** [comment]
Dev call: "canceled" with one "l".
