### ISSUE TITLE
Customizable required fields

### ISSUE THREAD

**Issue by koppor** [koppor/jabref#37]
When one aims to a high-quality bibtex file, one wants to have volume, number, and pages in articles, and pagetotal as well as ISBN in books. In normal operation, these fields are not required (and even non-existent in bibtex mode in the case of `@Book`). Maybe we need to modes of operation: normal mode and high-quality mode (where pre-defined fields getting required).

see https://github.com/JabRef/jabref/issues/316.
refs https://github.com/JabRef/jabref/issues/113.

**Comment by oscargus** [comment]
Yes, or a different warning color for "suggested" fields.

**Comment by koppor** [comment]
Works now with the new entry customization dialog.

The suggestion of the color should go into the "new concept for the entry editor" -- https://github.com/JabRef/jabref/issues/6856
