### ISSUE TITLE
Find unlinked files should ignore Thumbs.db etc.

### ISSUE THREAD

**Issue by koppor** [koppor/jabref#373]
Use case:

1. git init
1. git add library.bib
2. Have PDF files within that directory
3. Execute "find untlinked" files

Then all files `.git` are offered, too

- Basic implementation: Ignore a hard-coded list of files
- Advanced implementation: Read `.gitignore` in the root of the library path and obey it.

**Comment by koppor** [comment]
In my use-case blocked by https://github.com/JabRef/jabref/issues/3626

**Comment by calixtus** [comment]
The user can choose between the options *.pdf and *.* (All files). Imho one should get all files if one chooses all files. A clean solution for this issue would be to create an extra textfield "exclude files": "*.sys;thumbs.db"...

**Comment by calixtus** [comment]
Hi, sorry for the delay, just had some very stressful days. About your questions:
1. The files should be ignored when jabref is scanning for unlinked (attachable to an entry) files. Jabref should maybe read `.git` or `.gitignore` to know, which files should be ignored in a directory to scan.
2. There exists a dialog called "Find unlinked files" which already provides the scan logic etc. It should be easy to expand the logic to create a list of files to ignore
3. The end-user should be able to enable or disable some ignore option or have a list presented with files or filetypes to be ignored
4. See answer 1. Maybe be creative too.

Godspeed!

**Comment by prashant1712** [comment]
Hi, we are a group of students studying Master of Computer Science in University of Adelaide and we wanted to check if this issue is available/open for us to work on for our assignment.

**Comment by calixtus** [comment]
Since I did not hear about the other developer for months I believe this issue should be available to be solved.
Please remember to prepare your workspace according to our developer docs (especially checkstyle) so we can prevent a lot of questions and issue in the review process. Feel free to ask questions in our Gitter channel, if you don't understand something!

Have fun coding!

**Comment by prashant1712** [comment]
Thank you for your response. We'll start with the issue and we expect to submit the pull request by the first week of May 2022.

**Comment by calixtus** [comment]
Ok. The other dev thought he had to implement a completely new dialog. This is not necessary. Goal is to improve the existing one!
