### ISSUE TITLE
Add support for scite.ai

### ISSUE THREAD

**Issue by koppor** [koppor/jabref#375]
https://scite.ai/

> Check if a scientific paper has been supported or contradicted.

**Comment by koppor** [comment]
Example: https://scite.ai/search?page=1&q=maintaining%20dependencies%20across%20bpel%20fragments

![grafik](https://user-images.githubusercontent.com/1366654/75285951-db012980-5817-11ea-8377-cea22bf342a6.png)

**Comment by Siedlerchr** [comment]
Refs https://discourse.jabref.org/t/scite-integration/2624

**Comment by DanielS01ss** [comment]
Hi !
I would love work on this task if it is still available!

**Comment by koppor** [comment]
It is available (as you see in the status). Sorry for the late answer. I assume, you already worked on something else.

**Comment by taliashark77** [comment]
Hello, I'm a university student with an assignment to contribute to an open source repo, may I have a go at working on this issue?

**Comment by koppor** [comment]
@taliashark77 OK, I assign you.

**Comment by koppor** [comment]
@taliashark77 Please be advised that this a difficult issue. 

Guidance:

- First, implement a fetcher and test it. See https://devdocs.jabref.org/code-howtos/fetchers.html for a documentation.
- Second, implement the UI

For the UI, two options

A. Put on top in "Citation relations" tab (and rename to the tab to "Citation information"
  ![image](https://github.com/koppor/jabref/assets/1366654/775a161c-2f4b-4b7f-860c-99139b3f88f5)
B. Put a separate tab

B has the advantage that the APIs fetching the data are only called if the user wants it. It has the disadvantage that the user cannot get a complete overview of the "Citation information".

Nevertheless, go for option B and a separate tab. That will be more simpler to implement and test.

**Comment by koppor** [comment]
As a general advice for newcomers: check out [Contributing](https://github.com/JabRef/jabref/blob/main/CONTRIBUTING.md) for a start. Also, [guidelines for setting up a local workspace](https://devdocs.jabref.org/getting-into-the-code/guidelines-for-setting-up-a-local-workspace) is worth having a look at.

Feel free to ask here at GitHub, if you have any issue related questions. If you have questions about how to setup your workspace use JabRef's [Gitter](https://gitter.im/JabRef/jabref) chat. Try to open a (draft) pull-request early on, so that people can see you are working on the issue and so that they can see the direction the pull request is heading towards. This way, you will likely receive valuable feedback.

**Comment by taliashark77** [comment]
@koppor thanks for assigning me however I believe I do not actually know enough about APIs to work on this issue, is it ok if I'm unassigned and find another issue to work on for my assignment? Thanks

**Comment by u7500248** [comment]
Hey @koppor, because taliashark77 is no longer working on this issue can be assigned to it. Thanks

**Comment by koppor** [comment]
@u7500248 Done. Looking forward!
