### ISSUE TITLE
Create "File Magic Wizard"

### ISSUE THREAD

**Issue by koppor** [koppor/jabref#380]
When having a large libraries, a user wants to have all possible PDFs auto-linked to the respective bib entry

- Auto-link all files existing in the library directory
- Download all missing files

(Source: https://github.com/JabRef/jabref/pull/5216#issuecomment-557589116)

**Comment by flurfis** [comment]
This issue was recommended as part of our course “software engineering” from the university of Basel, and we decided to work on this issue.

But there are insecurities if we understood the issue correctly (especially the first point). So, we would like to clarify if our interpretation captures the meaning of the issue.

The File Magic Wizard allows the user to download all files from a library to the local computer of the user without creating dublicates in the target directory.
Concerning the point: “Auto-link all files existing in the library directory”
We understood it this way: 

- If a new library is created in JabRef, there will be a new field variable (related to the library) which contains a list with all links of the “download-source” from all files in the library.

- Every time a new BibEntry is added to the library, the corresponding link is added to the list.

- This list exists in case the whole library needs to be downloaded, so it is not necessary to iterate through the whole library. 

- The user can not view this list.

Thanks in advance!

**Comment by koppor** [comment]
Please think of a researcher having a .bib file with 1000 entries and 850 PDFs on his hard disk. He wants to be "quickly" be able to manage that chaos.

Example:

- Bib Entry A - no file attached (exists on hard disk)
- Bib Entry B - no file attached (does not exist on hard disk, but entry has DOI set)
- Bib Entry C - no file attached (does not exist on hard disk, entry has not DOI set, but DOI can be derived from title)
- Bib Entry D - no file attached (does not exist on hard disk, entry has not DOI set, DOI cannot be determined)
- Bib Entry E - file attached (exists on hard disk)
- Bib Entry F - file attached (does not exist on hard disk, but entry has DOI set)
- Bib Entry G - file attached (does not exist on hard disk, entry has not DOI set, but DOI can be derived from title)
- Bib Entry H - file attached (does not exist on hard disk, entry has not DOI set, DOI cannot be determined)

"file attached" means that the BibEntry has a `file` field. F to H are rare special cases.

(DOI could also be another identifier. Go into the code of JabRef and learn about document downloaders)

When executing the file wizard, the result is as follows:

- Bib Entry A - file attached
- Bib Entry B - file attached (was downloaded automatically, entry has DOI set)
- Bib Entry C - file attached (was downloaded automatically, entry has DOI set)
- Bib Entry D - no file attached
- Bib Entry E - file attached (exists on hard disk)
- Bib Entry F - file attached (was downloaded automatically, entry has DOI set, content of `file` field updated)
- Bib Entry G - file attached (was downloaded automatically, entry has DOI set, content of `file` field updated)
- Bib Entry H - no `file` field anymore

Log contains INFO entries on the actions done.

Your first assumption does not hold as JabRef does not (or seldomly) stores the URL location (typically)


Can you craft an exmaple with concrete BibTeX entries A to H and respetive files or would you need support for that? You find some bib entries at https://github.com/JabRef/jabref/blob/master/src/test/resources/testbib/jabref-authors.bib.

You should find some existing test case in the source when searchign for `unlinkedFilesTestBib.bib` (use <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>F</kbd>)

https://github.com/JabRef/jabref/blob/master/src/test/resources/org/jabref/util/unlinkedFilesTestBib.bib

## In other words

- "Auto-link all file existing" is a fuller automation for the functionality described at https://docs.jabref.org/collect/findunlinkedfiles#for-several-pdf-files. (settings described  at https://docs.jabref.org/finding-sorting-and-cleaning-entries/filelinks#auto-linking-files)
- "Download all missing files" is a "for each" on the functionality behind the search glasses described at ttps://docs.jabref.org/getting-started#adding-a-full-text-document

## Another example

The use case is an existing library, which should be quality-improved by JabRef. 

Think about a `.bib` file with 1000 entries and a folder structure as follows:

![grafik](https://user-images.githubusercontent.com/1366654/96804231-b7c26480-140e-11eb-8738-d1d05eeef6c7.png)

![grafik](https://user-images.githubusercontent.com/1366654/96804313-f526f200-140e-11eb-974e-3a6d2865d05f.png)

Now, the user has nonono clue, if a PDF is linked in the bib file.

It is important that the Wizard can be rerun and the wizard (seems to) rember the old state.

I especially remind on VDI 90, S16.ff:

> Inkrementelle Aufgabenbearbeitung ermögichen

(even though the text there describes a slightly different scenario. Nevertheless, I want to do some quality control on

**Comment by koppor** [comment]
This is strongly related to https://github.com/JabRef/jabref/issues/4652.

**Comment by koppor** [comment]
We keep the distinction between online search and local disk search. No File Magic Wizard will appear.
