### ISSUE TITLE
Quick change of default in Merge Entries Dialog

### ISSUE THREAD

**Issue by koppor** [koppor/jabref#385]
This is a follow-up to https://github.com/JabRef/jabref/pull/5688

> wie man die "Auswahl umkehren" kann, wenn man gefragt wird, was JabRef
> mit all den on-disk veraenderten Eintraegen machen soll: wenn man alle
> oder fast alle akzeptieren will, muss man, soweit ich sehe, jeden
> einzelnen anklicken. Ein "select all" button waere of sehr bequem.

This would bring us closer to the IntelliJ functionality (see https://github.com/JabRef/jabref/pull/5688#issuecomment-568295413)

For clarification "Einträge" means the yellow marked area

![grafik](https://user-images.githubusercontent.com/1366654/71647190-10473a80-2cf3-11ea-93c6-47273bdaf61d.png)

**Comment by Siedlerchr** [comment]
Fixed now in master
