### ISSUE TITLE
Add LOBID fetcher

### ISSUE THREAD

**Issue by koppor** [koppor/jabref#386]
https://gist.github.com/zuphilip/66699b4515e4d0094f7333240948b108

<blockquote class="twitter-tweet"><p lang="en" dir="ltr">A small <a href="https://twitter.com/zotero?ref_src=twsrc%5Etfw">@zotero</a> script that performs author lookups in <a href="https://twitter.com/lobidOrg?ref_src=twsrc%5Etfw">@lobidOrg</a> API and show possible matches from the <a href="https://twitter.com/gndnet?ref_src=twsrc%5Etfw">@gndnet</a> : <a href="https://t.co/Byk7vbDrhz">https://t.co/Byk7vbDrhz</a></p>&mdash; Philipp Zumstein (@zuphilip) <a href="https://twitter.com/zuphilip/status/1210525155342143489?ref_src=twsrc%5Etfw">December 27, 2019</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

Their Twitter handle: https://twitter.com/lobidOrg?s=20

Somehow related to #472

**Comment by guenesaydin** [comment]
Hello Oliver,

pursuant for the Software Engineering course at the University of Basel, a group chose this as their project. They are quite confused what they should actually do, like codewise. Do you have any examples or clarify this a bit more? They have to specify their project until Sunday so if its possible to get an answer before this would be very useful. Thank you very much for the opportunity to work on JabRef again! 

Best, 

Günes

**Comment by koppor** [comment]
(Note that this issue is not contained in https://github.com/JabRef/jabref/projects/9 and also has the label "needs-refinement". Thus, it is a more harder task than typical student tasks).

This is a typical (hard) requirements engineering task. Find general information on lobid at https://lobid.org/. The issue "on the other side" is https://github.com/hbz/lobid/issues/277.

The tewwet above contains "author lookups in @lobidOrg API", which points to some author lookup thing. This could cause a rewrite of JabRef's handling authors. JabRef could have a separate author management to avoid duplicates and to enable lookup of data of authors. -- We do not do that in this task.

The lobid API is described at https://lobid.org/resources/api. This turns the task into "Add a fetcher for LOBID". See https://github.com/JabRef/jabref/blob/master/src/main/java/org/jabref/logic/importer/fetcher/SpringerFetcher.java for an example fetcher. Find other fetchers in that directory.

The user-facing side for existing fetchers is documented at https://docs.jabref.org/collect/import-using-online-bibliographic-database.

**Comment by koppor** [comment]
See https://github.com/JabRef/jabref/pull/8700 for a PR introducing a new fetcher

**Comment by aqurilla** [comment]
Hi! I would like to take up this issue
