### ISSUE TITLE
Integrate or remove TextAnalyzer

### ISSUE THREAD

**Issue by koppor** [koppor/jabref#39]
See https://github.com/JabRef/jabref/pull/377#issuecomment-158553283 for a discussion.

**Comment by koppor** [comment]
The place to integrate is "BibTeX" -> "New entry from plain text"

**Comment by koppor** [comment]
As stated athttps://github.com/koppor/jabref/issues/14#issuecomment-162243500, [PRRV](http://jabrefprrvp.sourceforge.net/) uses the complete reference text. Maybe, the algorithm of PRRV can be directly included in JabRef, too.

**Comment by simonharrer** [comment]
unused
