### ISSUE TITLE
When opening a library and a .bak file is found -> show the diff

### ISSUE THREAD

**Issue by koppor** [koppor/jabref#391]
Instead of just asking to load the backup, show the diff to the backup.

Use the file conflict dialog (appears when a file is changed externally).

**Comment by koppor** [comment]
If there is no diff, the dialog should not be shown.

**Comment by koppor** [comment]
Still happening on today's main build:

![grafik](https://user-images.githubusercontent.com/1366654/112989011-c272e980-9164-11eb-83ff-c902629dc082.png)

**Comment by Siedlerchr** [comment]
The merge dialog should now be shown. 
There needs to be warning as well:

WARNING: Restore from backup will overwrite your current library

**Comment by Siedlerchr** [comment]
Duplicate of https://github.com/JabRef/jabref/issues/9066
