### ISSUE TITLE
"Pull changes from shared database" should only be activated when connected to a shared DB

### ISSUE THREAD

**Issue by koppor** [koppor/jabref#393]
I am not connected to a shared DB, so I cannot pull any changes. The button should be disabled.

![grafik](https://user-images.githubusercontent.com/1366654/73556371-9cae5f80-444f-11ea-8345-a87c7ad8c560.png)

**Comment by u7229988-Rabie** [comment]
Hi, I am a first-time contributor, can I be assigned to this issue? I am a university student whose assignment requires me to contribute to open-source projects.

**Comment by u7631839** [comment]
Hello, I'm a new contributor, and I will carefully read the contribution guidelines. Could you please assign this issue to me? @ThiloteE

**Comment by u7631839** [comment]
I think this issue have been fixed by [JabRef/jabref/pull/5974](https://github.com/JabRef/jabref/pull/5974) @ThiloteE

**Comment by ThiloteE** [comment]
You are right. Thank you @u7631839. Let's close this issue.

**Comment by u7631839** [comment]
Hello, I'm a new contributor, and I will carefully read the contribution guidelines. Could you please assign this issue to me?
