### ISSUE TITLE
It would be nice if the color of the icons could be configurable

### ISSUE THREAD

**Issue by koppor** [koppor/jabref#40]
Currently, the color of the icons is hard-coded in a constant. It would be nice if one could change the color via a config option. Or should we leave that open for special JabRef distributions? :sunglasses: 

![petrol](https://cloud.githubusercontent.com/assets/1366654/11321013/90690070-90af-11e5-8858-d558e1fa8142.png)

![blue](https://cloud.githubusercontent.com/assets/1366654/11321015/92d8eb4a-90af-11e5-83dd-4a97fc521da4.png)

**Comment by stefan-kolb** [comment]
Red christmas edition v3.1 :smile:

**Comment by simonharrer** [comment]
Only for the christmas editions ;)
