### ISSUE TITLE
Add icons to all dialogs

### ISSUE THREAD

**Issue by koppor** [koppor/jabref#402]
![grafik](https://user-images.githubusercontent.com/1366654/74927920-cddbd900-53d8-11ea-8879-c97f6b58b0cf.png)

**Comment by BugMan-111** [comment]
Hello, I am interested in this issue. Would you please move this issue to "reserved" Thanks.

**Comment by koppor** [comment]
As a general advice for newcomers: check out [Contributing](https://github.com/JabRef/jabref/blob/main/CONTRIBUTING.md) for a start. Also, [guidelines for setting up a local workspace](https://devdocs.jabref.org/getting-into-the-code/guidelines-for-setting-up-a-local-workspace) is worth having a look at.

Feel free to ask here at GitHub, if you have any issue related questions. If you have questions about how to setup your workspace use JabRef's [Gitter](https://gitter.im/JabRef/jabref) chat. Try to open a (draft) pull-request early on, so that people can see you are working on the issue and so that they can see the direction the pull request is heading towards. This way, you will likely receive valuable feedback.

**Comment by BugMan-111** [comment]
thanks for reserving this issue for me

**Comment by BugMan-111** [comment]
Hi @koppor, It appears that someone has added icons to all dialogs
![image](https://github.com/koppor/jabref/assets/83073246/11dd7be1-982e-45d0-80a6-f47c0822ed19)
![image](https://github.com/koppor/jabref/assets/83073246/6cc54eb9-fce4-4e8a-a9bf-a990ecd6e366)
![image](https://github.com/koppor/jabref/assets/83073246/fbb1510f-b4e1-47ef-b3a8-7c558936bacf)
![image](https://github.com/koppor/jabref/assets/83073246/d92f093d-432c-4af9-a808-67c452fdedee)

**Comment by koppor** [comment]
Thank you for checking! Sometimes it turns out that thee year old issues are solved in the meantime without notice .

**Comment by koppor** [comment]
Your screenshots are an indicator that https://github.com/koppor/jabref/issues/149 still is unsolved!

**Comment by BugMan-111** [comment]
@koppor No Worries !!
