### ISSUE TITLE
Ensure that Postgres is the default database to create

### ISSUE THREAD

**Issue by koppor** [koppor/jabref#409]
and not recommend MySQL ^^

![grafik](https://user-images.githubusercontent.com/1366654/201219939-0aeff118-2bca-4148-a5fb-7b41080e678c.png)

Refs https://github.com/JabRef/jabref/issues/6014

**Comment by koppor** [comment]
Currently MySQL

![grafik](https://user-images.githubusercontent.com/1366654/78509009-3fa29300-778b-11ea-8470-4c1e940f3835.png)

**Comment by fuyuanyuanchn** [comment]
Hello, I am part of a group in a course at The university of Adelaide. We would like to contribute, and hopefully close this issue as part of our open source contribution project. We estimate that we may submit our initial pull request by late April / early May.

**Comment by koppor** [comment]
Sure!

As a general advice for newcomers: check out [Contributing](https://github.com/JabRef/jabref/blob/main/CONTRIBUTING.md) for a start. Also, [guidelines for setting up a local workspace](https://devdocs.jabref.org/getting-into-the-code/guidelines-for-setting-up-a-local-workspace) is worth having a look at.

Feel free to ask here at GitHub, if you have any issue related questions. If you have questions about how to setup your workspace use JabRef's [Gitter](https://gitter.im/JabRef/jabref) chat. Try to open a (draft) pull-request early on, so that people can see you are working on the issue and so that they can see the direction the pull request is heading towards. This way, you will likely receive valuable feedback.

**Comment by fuyuanyuanchn** [comment]
I am sorry. I accidentally clicked the unassigned button. Could you please assigned me again. I am so sorry about that.
