### ISSUE TITLE
Allow drag'n'drop of .bib to open file on empty JabRef

### ISSUE THREAD

**Issue by koppor** [koppor/jabref#424]
![grafik](https://user-images.githubusercontent.com/1366654/76664529-ff356800-6584-11ea-9b3c-0d42452d9f1e.png)

**Comment by btut** [comment]
Works for me! I guess it was already implemented.
![Screenshot from 2021-06-07 13-13-12](https://user-images.githubusercontent.com/10479048/121007419-4f07dc80-c792-11eb-8505-cd2754dbdf43.png)

**Comment by koppor** [comment]
Thank you for updating!

`dark.css` seems to be broken ^^

![grafik](https://user-images.githubusercontent.com/1366654/121093769-cb7bd900-c7ed-11eb-9621-788115f18133.png)

**Comment by btut** [comment]
`dark.css seems to be broken ^^`
True, but that bug is not exclusive to JabRef I'm afraid.
