### ISSUE TITLE
File history size preference

### ISSUE THREAD

**Issue by oscargus** [koppor/jabref#43]
I might be blind, but I can not find where the file history size is changed. For some reason, it is set to three for me now (probably because my test failed before it was reset).

1) Should it be changeable?
2) Which tab should it be in?

**Comment by koppor** [comment]
Here, I tested it up to five (5) entries. No issues. No configuration for that. Always 9 entries.

The only issue I have is that the menu is not consistent with other apps like NotePad++. There, I can press `ALT+f` and then `1` to select the first file in file history. Maybe, the "recent files" menu can just be included in the "Files" menu?

**Comment by oscargus** [comment]
Sorry, I wasn't clear enough. There is a preference item for the file size:
`public static final String HISTORY_SIZE = "historySize";`
which is initially set to 8
`defaults.put(HISTORY_SIZE, 8);`

However, I do not know of any way to set this in the UI.

(In the test of FileHistory I change it, and later restore it. However, as the test broke, it wasn't restored. Is there an @After method BTW? Maybe it is better to copy all preferences affected in the test in @Before and then reset them in @After?)

**Comment by koppor** [comment]
I think, this should **not** be configurable (and I haven't seen any configuration for it). We should make that a global constant and move away the setting from the preferences.

Regarding the preferences in general: Yes, use `@After`. See https://github.com/JabRef/jabref/wiki/Code-Howtos#test-cases

**Comment by oscargus** [comment]
I agree. A bit more tedious to write the test, but avoids the hassle of failing a test and messing up the preferences (as it cannot be changed). :-)

OK to move the constant to FileHistory instead of JabRefPreferences?
