### ISSUE TITLE
Constructor of Bibtexentry should set citeKey, shouldn't it

### ISSUE THREAD

**Issue by koppor** [koppor/jabref#44]
When reading following statement:

```
    BibtexEntry e = new BibtexEntry("id", BibtexEntryTypes.ARTICLE);
```

What should `e.getCiteKey()` be?

I have expected `id`, but it was `null`. Reason: the internal id of an entry is not the cite key. I think, this has reasons. For example, when changing the key of an entry or making the entry invalid, what should happen? As a quick fix, I would suggest that the constructor should call `this.setField(KEY_FIELD, id);`.

Alternatively, we should use Integers (Longs because of large databases?) as Ids as done in https://github.com/magsilva/jabref/commit/9bb2074de7a42765843ad3628c60d54a906e29c6. Refs https://github.com/JabRef/jabref/issues/112.

**Comment by simonharrer** [comment]
Hm, you mean a default for the bibtex key if nothing is set? So that there is always a bibtex key?

**Comment by koppor** [comment]
The key is not always present (leading to user issues, e.g., https://github.com/JabRef/jabref/issues/8645). Nevertheless, we need to handle that case somehow in JabRef. We have a builder in place. Thus, this issue is obsolete.
