### ISSUE TITLE
Add ADR to stick on Gradle 6.3

### ISSUE THREAD

**Issue by koppor** [koppor/jabref#440]
Refs https://github.com/JabRef/jabref/pull/6431

**Comment by koppor** [comment]
We did not add an ADR and fixed that Gradle 6.5 can be used.

According to https://github.com/JabRef/jabref/pull/7097#issue-521038214, we are blocked by https://github.com/openjfx/javafx-gradle-plugin/issues/89

**Comment by Siedlerchr** [comment]
We can upgrade https://github.com/java9-modularity/gradle-modules-plugin/issues/165#issuecomment-753667292

I tested that in the modularity issue branch, but had the impression that JabRef was slower afterwards
