### ISSUE TITLE
Internal storage of field names

### ISSUE THREAD

**Issue by koppor** [koppor/jabref#45]
When issuing `.setField("TEST", "value"` and doing a `.getField("test")`, I'd expect the result to be `value` as BibTeX field names are case insensitive. However, JabRef currently returns `null`. Should we change the behavior? Should we simply add `assert`ions or just add comments to the method?

**Comment by lenhard** [comment]
I aggree and implemented a conversion in 720b2d867decb001fb78a9548fd13839c4f4892f

Fields are now always accessed via their lowercase description and input parameters are normalized accordingly. The access now works with `TEST`, `TeSt` or the like. 

Additionally, the commit adds a little more null validation in `BibtexEntry`. If you input null, `BibtexEntry` replies with a `NullPointerException`.
