### ISSUE TITLE
Add delete button

### ISSUE THREAD

**Issue by koppor** [koppor/jabref#46]
There is only a `cut` button, but no deletion button.

**Comment by simonharrer** [comment]
Can you please elaborate? There is a delete button for the entry itself. Why whould you need an additional delete button?

**Comment by koppor** [comment]
Could you please point me to the delete button in the toolbar: I'm too dumb to find it.

![toolbar](https://cloud.githubusercontent.com/assets/1366654/11420649/b3ee1480-942f-11e5-9880-10f5a617c78a.png)

**Comment by simonharrer** [comment]
Ah, context toolbar. :)

In the toolbar, there is no button, but in the menu there is. Hm, yes, why not. But normally, one uses the delelte key on the keyboard anyway (probably).

What I see from a UI perspective: delete only works for entries. It does not work for selected text, hence, it is not completely similar to the cut, copy, past actions. 

Where would you put the delete icon?

**Comment by koppor** [comment]
Position: right of "Edit entry". Then, we have, new, edit, delete. This would also make the context clear and such that "delete" is applicable to the entry only.

**Comment by simonharrer** [comment]
sounds good.
