### ISSUE TITLE
Add support of markdown in JavaDoc comments

### ISSUE THREAD

**Issue by koppor** [koppor/jabref#49]
Include [Pegdown Doclet](https://github.com/Abnaxos/pegdown-doclet) to enable Markdown in JavaDoc comments.

**Comment by simonharrer** [comment]
unnecessary, from my point of view. 

We should stick to the official javadoc language using html tags sparsely.

**Comment by matthiasgeiger** [comment]
I agree with Simon.

**Comment by koppor** [comment]
Due to github, markdown gets more and more popular among developers. Homepages are migrated to gh-pages, because markdown is easier to maintain.

I have to confess that my only current use case are lists. I can do them using `<ul>`. If **three** or more contributers want to do markdown, we'll integrate Peddown, would that be OK?

**Comment by simonharrer** [comment]
We should just use Markdown for the help pages. There, the fit is perfect.

**Comment by koppor** [comment]
Yes, this already planned. Implicitly stated at https://github.com/JabRef/jabref/issues/111. The homepage contains the help and the homepage is converted to markdown.
