### ISSUE TITLE
Installer: Enable resetting of preferences and deletion of settings

### ISSUE THREAD

**Issue by koppor** [koppor/jabref#50]
When installing JabRef, the user should be asked whether existing settings should be reset. Implementation: Delete registry key `HKEY_CURRENT_USER\SOFTWARE\JavaSoft\Prefs\net\sf\jabref`.

When uninstalling JabRef, "tidy up thoroughly" (such as MikTeX offers) should be offered. Then, the registry key `HKEY_CURRENT_USER\SOFTWARE\JavaSoft\Prefs\net\sf\jabref` is deleted, too.

**Comment by Siedlerchr** [comment]
Additonally, it should have the option to uninstall previous JabRef Versions (e.g. 2.10, 2.11)

**Comment by simonharrer** [comment]
We changed the installer, hence, it may be complicated to uninstall 2.x installations.

**Comment by koppor** [comment]
Install4J can IMHO be scripted. There, we could check if the installation folder already exists. Or if the Windows program registry somehow knows about old installations of JabRef. If JabRef 2.x exists, the installer should ask if it should call the old uninstaller.

asking-for-a-pull-request :innocent:

**Comment by koppor** [comment]
Not possible to to with jpackage.
