### ISSUE TITLE
Filename to delete should be shown completely

### ISSUE THREAD

**Issue by koppor** [koppor/jabref#534]
When deleting a file, the file path is sometimes too long to fit in the title of the dialog.

![grafik](https://user-images.githubusercontent.com/1366654/140174782-6548e03e-8f99-4223-91f3-96aa7c7afa20.png)

Proposal: Show the filename also in the dialog text

**Comment by Racheal7** [comment]
Hi Koppor, I am really interested in this issue and I'd like to contribute. Could you please assign this issue to me? Thank you very much.

**Comment by Racheal7** [comment]
Hi Oliver, 

I have looked into this issue and come up with several solutions to improve the UI. 

1. Delete the file path in the dialog title and replace it with "Delete File". Add the full file path in the text. 

![Add file name to text](https://user-images.githubusercontent.com/45301647/197337197-a5c81aa4-4271-4634-ad77-34093dd1bd93.png)
 

3. In the dialog title, replace the full file path with only the file name, and add the full file path in the text. 

![Add only file name in title](https://user-images.githubusercontent.com/45301647/197337217-0bfbed4f-8587-413e-b5be-4bd876f77422.png)

5. Just like you suggested in the description, we can keep the file path in the title and add it to the text. 

![Only add file path in text](https://user-images.githubusercontent.com/45301647/197337372-011d1509-a4bb-40a9-879a-ef3dfe776578.png)

Personally, I prefer the second solution as it's neater, but I'd love to know what you think.
