### ISSUE TITLE
When clicking on download file from URL, the URL in the clipboard should be filled in the field

### ISSUE THREAD

**Issue by koppor** [koppor/jabref#535]
My workflow: I copy the URL of a PDF into the clipboard (e.g., https://mediatum.ub.tum.de/doc/1521926/1521926.pdf). Then, I click on "download file from URL". Then I need to paste the URL again.

![grafik](https://user-images.githubusercontent.com/1366654/140176914-1d67d452-1364-4071-bab7-634cb930a5af.png)

Would be great if the initial value of the field would be the clipboard text (if it is a URL).

**Comment by Gpax971** [comment]
Could I please be assigned to this issue?
