### ISSUE TITLE
Toggle Settings have strange behavior

### ISSUE THREAD

**Issue by simonharrer** [koppor/jabref#54]
When having two tabs, one can set that the groups window should be seen in one tab but not in the other. This is strange. I would propose to either always show it or never. Same is true for the web search.

**Comment by Braunch** [comment]
What I did:
1. Open two databases
2. Open the groups window in one of them
3. switch to the other db
4. close groups window
5. switch back -> groups window is gone
Same behaviour the other way round and with the global search. I can't reproduce the behavior. it seems to be fixed. Do we miss a reference to a PR here?

**Comment by matthiasgeiger** [comment]
Yes, this can be closed.
