### ISSUE TITLE
Add CLI option: --jump-to-entry key

### ISSUE THREAD

**Issue by koppor** [koppor/jabref#540]
There should be command line interface (CLI) option to jump to an entry.

Use case: I have TeXStudio opened and want to jump to the respective BibEntry in JabRef.

![grafik](https://user-images.githubusercontent.com/1366654/140231093-7702e268-3054-4d22-91a6-8c3cc3cdf263.png)

In other words: I request the opposite functionality of https://docs.jabref.org/cite/pushtoapplications

The current CLI does not offer it - according to https://docs.jabref.org/advanced/commandline

**Comment by u7282852** [comment]
Hi I'm a university student and new to contributing. I would love to work on this issue if possible.

**Comment by koppor** [comment]
@u7282852 Thank you for choosing JabRef. Here some general hints. Looking forward to your contribution.

As a general advice for newcomers: check out [Contributing](https://github.com/JabRef/jabref/blob/main/CONTRIBUTING.md) for a start. Also, [guidelines for setting up a local workspace](https://devdocs.jabref.org/getting-into-the-code/guidelines-for-setting-up-a-local-workspace) is worth having a look at.
            
Feel free to ask here at GitHub, if you have any issue related questions. If you have questions about how to setup your workspace use JabRef's [Gitter](https://gitter.im/JabRef/jabref) chat. Try to open a (draft) pull-request early on, so that people can see you are working on the issue and so that they can see the direction the pull request is heading towards. This way, you will likely receive valuable feedback.

Additional hint: This month, it's [#hacktoberfest](https://hacktoberfest.com/).

**Comment by u7282852** [comment]
Hi, I just realised that I have been doing my work on the main Jabref/jabref project instead of the koppor/jabref project. Should I clone the correct repository and move my changes over, or can I still open a PR on the main project?

**Comment by koppor** [comment]
JabRef/jabref is really fine - it is the intention. Thus, just continue. - Please ensure that you reference the issue by the **full** URL.

We are working to move alle the issues to the other repository, but that takes time.

**Comment by u7282852** [comment]
Hi I just submitted a draft pull request for this issue. It turns out I have forked Koppor/jabref though have followed the workspace instructions for the normal project so the pull request seems to be submitted for Koppor/jabref. Let me know if I need to do anything to fix this. Thanks

**Comment by koppor** [comment]
>so the pull request seems to be submitted for Koppor/jabref.

To fix this:

1. Navigate to https://github.com/JabRef/jabref/pulls
2. Click on "New Pull Request"
3. Click on "compare across forks"\
    ![image](https://github.com/koppor/jabref/assets/1366654/ac1f0e3b-239c-4608-8656-3766308f7c62)
4. Choose JabRef (1) / main (2) / u7282852 (3) / issue541-jump-to-entry-cli (4) \
    ![image](https://github.com/koppor/jabref/assets/1366654/c4e45996-ab19-4d07-a7eb-5bd250a11a7b)
5. Adapt description. Use `Fixes https://github.com/koppor/jabref/issues/540` to enable autolinking

---

Side question: Can you give me a hint how to improve the text so that contributors as you use `Fixes` instead of `Adresses` in the PR description?

![image](https://github.com/koppor/jabref/assets/1366654/d1435c2c-6a8a-4061-bc44-85eed5b97d18)

Maybe, we need to make the text more clear? Longer is not an option I think.

**Comment by u7282852** [comment]
Thank you for your help! I will implement these changes. I just assumed "fixed" might be only for issues relating to bugs or problems, considering this is more of a new feature I wrote "addresses" but I will switch them to fixed now.
