### ISSUE TITLE
Dropdown for file types at "Find Unlinked Files" should not contain .bib

### ISSUE THREAD

**Issue by koppor** [koppor/jabref#547]
As user, I collect my papers as `.pdf`  or `.html`, but not as `.bib`, because BibTeX is the meta data

![grafik](https://user-images.githubusercontent.com/1366654/147218561-65d6280f-155e-423b-b6ef-693bf788ccad.png)

**Comment by Simone-Thai** [comment]
Hi, could I be assigned to this issue?

**Comment by Simone-Thai** [comment]
Hi Koppor, 
I'm planning to remove the BibTeX option and add in both the HTML and TXT standard file types, I was wondering about your thoughts on this?

**Comment by Simone-Thai** [comment]
I've noticed `ImportHandler` doesn't currently check html files. There currently isn't a method to parse a html file in `EnternalFilesContentImporter` and there are no importers for html files, however there is a `citaviXmlImporter` which may be relevant to this issue. 
I believe that this is outside the scope of this issue, but I wanted a second opinion on this?

**Comment by koppor** [comment]
> Hi Koppor, I'm planning to remove the BibTeX option and add in both the HTML and TXT standard file types, I was wondering about your thoughts on this?

This is OK. Selection of multiple file types should be possible.

Additionally, `*.md`, should also be possible as Markdown becomes more and more prominent

**Comment by koppor** [comment]
> I've noticed `ImportHandler` doesn't currently check html files.

The file could just be linked without any other meta data.

> however there is a `citaviXmlImporter` which may be relevant to this issue. 

HTML is a a format with many options to put content in. There is no easy way to parse HTML. One could write a parser checking the `<head>` content of HTML. Contents such as `title` is standardized - and this could be read very easy. (See https://html.spec.whatwg.org/multipage/dom.html#metadata-content-2 for details)

For `.txt`, this is more complex.

**Comment by koppor** [comment]
In case a file type is not recognized at import, the name of the file (without extension) should be used as `title` in BibTeX.

**Comment by Simone-Thai** [comment]
I've added a markdown file option:
<img width="626" alt="Screen Shot 2022-10-28 at 4 05 13 pm" src="https://user-images.githubusercontent.com/110802893/198507290-3afdcafd-7d4d-4882-8a6a-3fa43c57db0b.png">
So far I've been working in the `UnlinkedFilesDialogViewModel` class but are there other areas that I need to work on too?

**Comment by Simone-Thai** [comment]
Hi Koppor, 
I am planning to add an icon to the markdown file so I was wondering if you had any suggestions to go about this?

**Comment by koppor** [comment]
Yes, its good. I have no other Markdown icon in mind (and I did not google :p)
