### ISSUE TITLE
PdfPreviewPanel must be checked

### ISSUE THREAD

**Issue by matthiasgeiger** [koppor/jabref#55]
net.sf.jabref.gui.PdfPreviewPanel is quite a mess... 

Preview rendering seems to be triggered for each file not only for PDFs
Exceptions are not logged but there are still the auto-generated stack traces etc.

Maybe one of the three authors of the class will have a look?
`Copyright (C) 2012 Meltem Meltem Demirköprü, Ahmad Hammoud, Oliver Kopp`
:wink:

**Comment by simonharrer** [comment]
@koppor

**Comment by koppor** [comment]
IMHO the only way to fix that is to remove that and to integrate an external viewer somehow. Docear, for example, [relies on PDF-XChange Viewer](http://www.docear.org/support/user-manual/#PDF-XChange_Viewer).

**Comment by tobiasdiez** [comment]
PdfPreview was removed
