### ISSUE TITLE
Found text should be highlighted in green or in with yellow background, because red is a signal color for errors

### ISSUE THREAD

**Issue by koppor** [koppor/jabref#552]
![grafik](https://user-images.githubusercontent.com/1366654/147221476-5c5e30c1-e626-4f37-9c72-b67014066ee8.png)

**Comment by u7232539** [comment]
@koppor Hi, I am working on a uni assignment and I would like to work on this issue. Can you please assign it to me? Also is there anything I should keep in mind while working on this issue? Thank you.
