### ISSUE TITLE
Web search results should render the BibTeX too

### ISSUE THREAD

**Issue by koppor** [koppor/jabref#560]
Example search "Vino4TOSCA" on "Collection of Computer Sciene Bibliographies"

![image](https://user-images.githubusercontent.com/1366654/164985244-3936ba65-07cc-41bd-b7d0-a9e2511d4fa0.png)

As user, I wonder, which entry contains the most information.

I would like to have a) the BibTeX information or b) a list of fields (as soon as I click on an entry).

**Comment by nooynayr** [comment]
Hello, I've gone through the [contributing page](https://devdocs.jabref.org/contributing) and the [setup page](https://devdocs.jabref.org/getting-into-the-code/guidelines-for-setting-up-a-local-workspace/). Would I be able to be assigned for this issue? 

I'd like to maybe have some pointers on where to start with this issue if possible as well?

**Comment by taliashark77** [comment]
Hello, I would also be interested in working on this issue for my university assignment, please let me know it would be ok for me to work on this

**Comment by koppor** [comment]
@nooynayr Was first, sorry @taliashark77.

@nooynayr Please give feedback within two days if you really work on this. Otherwise, I will free up the issue again.

**Comment by nooynayr** [comment]
@koppor I've looked into the repo and I've compiled the project so that I can use JabRef. Which classes would I need to look into in order to resolve this issue? I've looked at the search folder under gui so far.

**Comment by koppor** [comment]
@nooynayr IntelliJ offers <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>F</kbd> to search for text. You can use the text "Select the entries to be imported" to find the classes. Maybe you should also give JavaFX give a read: https://devdocs.jabref.org/code-howtos/javafx.html

**Comment by nooynayr** [comment]
@koppor Could you unassign me from this issue?

**Comment by MrMachiei** [comment]
Hi all, hope everything is going well! I'm really interested in tackling this issue as a beginner, could I take it?

**Comment by MrMachiei** [comment]
Hi @koppor, I'm working on the issue now, could you please give me an example of how would you like to Bibtex information be presented after clicking on an entry)?

**Comment by koppor** [comment]
@MrMachiei Just the plain BibTeX, like in the entry editor.

![image](https://github.com/koppor/jabref/assets/1366654/77f44b7a-b780-436e-b188-f8b28c822c5b)

Place it below the list and the buttons ("Select all entries", ...)

**Comment by MrMachiei** [comment]
Hi @koppor, I created the PR: https://github.com/JabRef/jabref/pull/10784
