### ISSUE TITLE
drag and drop of a group to a the groups field should add the paper to the dropped group

### ISSUE THREAD

**Issue by koppor** [koppor/jabref#569]
![image](https://user-images.githubusercontent.com/1366654/169623829-c8f32818-296a-4ce9-9334-2772eaa0dcc8.png)

**Comment by bryce-carson** [comment]
The blurring of the screenshot makes it difficult to see what is shown.

What is the intent of the image? What is the full meaning of the title of this issue?

**Comment by koppor** [comment]
See the group "demo group" in the screenshot?

![image](https://user-images.githubusercontent.com/1366654/230625946-505378b8-7c49-4d5a-895d-a02148a18ab7.png)

See that that the article is not beloging to the group "demo group"?

Switch tot he tab "General", scroll down to "Groups", now drag and drop the group "demo group":

![image](https://user-images.githubusercontent.com/1366654/230626083-35eec743-d45d-48e4-9bdc-a5d4d943eb4e.png)

- Expected result: Entry is added to the group "demo group"
   ```bibtex
   @Article{ostgaard2002,
     journal = {Phys Rev B},
     title   = {energy},
     year    = {2012},
     month   = sep,
     groups  = {demo group},
   }
   ```
- Actual result: Dropping not allowed

Note that drag and drop of an entry to a group works:

![image](https://user-images.githubusercontent.com/1366654/230626242-a1ea53f8-2b97-452c-ac66-a53cc6dc9238.png)

**Comment by wy8881** [comment]
Hi,
I want to try this issue and now I'm checking with the code. I have some questions and it would be greatly appreciated if anyone can give me some advice.
1. According to the comment in GroupTreeView.java, it put the group nodes as content. But it seems like I can only get the name of the group. 

![Image](https://github.com/koppor/jabref/assets/88151174/d53c99f2-6183-4506-9761-0a27b2b061da)
I wonder if there is a way I can get the variable row, and therefore I can use the same method in GroupTreeView.java to move to the group.


![Image](https://github.com/koppor/jabref/assets/88151174/487f1e7f-9044-4cc8-b37e-a76a8dbdfd5e)




2.  I notice that if I change the group directly in General-Group, this paper will be moved to this group. If the group's name is the only thing I can get while dragging, can I add the name to this field directly to move the paper? But I'm not sure what functions are triggered when I change the content manually. It's great if you can give me some hints.

**Comment by k3KAW8Pnf7mkmdSMPHz27** [comment]
> I wonder if there is a way I can get the variable row, and therefore I can use the same method in GroupTreeView.java to move to the group.

I don't understand, what is the "variable row"?

> If the group's name is the only thing I can get while dragging, can I add the name to this field directly to move the paper?

Yes, this should be possible as long as you can access the BibEntry object, it is responsible for notifying listeners 

https://github.com/JabRef/jabref/blob/424ff1c7cac2db2cc8d4321253bf6614cd4984b3/src/main/java/org/jabref/model/entry/BibEntry.java#L567-L574

**Comment by wy8881** [comment]
Hello, thanks for your reply. By "row" I mean this"


![Image](https://github.com/koppor/jabref/assets/88151174/fe3f6e0e-7da3-41c8-a8aa-86df044ea087)

Although I still don't know where this variable is from, it seems nothing to do with my issue.
Your advice is helpful and now I know how to add a group. However, this drag or drop will happen when dragging the group to the EntryEditor panel instead of dragging it to the exact group field inside General Tab. I try to add setOnDragDropped() function to a table, but it seems I can't do it. It'll be helpful if someone can give me some advice.

**Comment by k3KAW8Pnf7mkmdSMPHz27** [comment]
> Although I still don't know where this variable is from, it seems nothing to do with my issue.

Probably not. If you look at when the `ViewModelTreeTableRowFactory` is created, you'll notice it is calling `install` at the end. Following the method call chain will lead you to that it comes from `TreeTableView`, a JavaFX class that supplies a `TreeTableView` and a `TreeTableRow`, so it looks like it is built-in to the TreeTable of JavaFX.

**Comment by wy8881** [comment]
Thank you, got it.
