### ISSUE TITLE
Generate bibtex key should always work

### ISSUE THREAD

**Issue by koppor** [koppor/jabref#575]
![image](https://user-images.githubusercontent.com/1366654/172934811-5ba1f15b-3244-415b-a4d4-a769e683ae79.png)

does not generate bibtex key even if

![image](https://user-images.githubusercontent.com/1366654/172934909-564059c3-ba4d-49a0-a2aa-5a4293e39162.png)

**Comment by morganteg** [comment]
Hi Oliver,

I tried to reproduce the bug without success, with the following test case:

New Article -> General -> DOI -> https://doi.org/10.11113/jt.v70.3512 -> "Get bibliographic data from DOI"

The BibTex key ("Mohd_Shaid_2014") seems to be correctly generated:
`
@Article{Mohd_Shaid_2014,
  author    = {Syed Zainudeen Mohd Shaid and Mohd Aizaini Maarof},
  journal   = {Jurnal Teknologi},
  title     = {Malware Behaviour Visualization},
  year      = {2014},
  month     = {sep},
  number    = {5},
  volume    = {70},
  doi       = {https://doi.org/10.11113/jt.v70.3512},
  publisher = {Penerbit {UTM} Press},
}
` 
What do you think?

Regards.

**Comment by koppor** [comment]
You are right. Someone seemed to have fixed it within the last 9 months 🎉.
