### ISSUE TITLE
Dialog Title: Save File vs. Edit File Link

### ISSUE THREAD

**Issue by matthiasgeiger** [koppor/jabref#58]
The same dialog shown in three different use cases:
After hitting "Auto" in the editor to edit and save the file downloaded.
AND
After clicking "+" (add file). 
AND
Double click on existing file link.

The title is always "Save file" - was previously "Edit file link".

@stefan-kolb Have you changed the title?

Should we restore "Edit file link"? Or use a different title depending on the context?

**Comment by stefan-kolb** [comment]
I probably changed it to better reflect most situations, yeah.

**Comment by simonharrer** [comment]
Depending on context would make sense.

**Comment by koppor** [comment]
I think, this is now solved. Please reopen with screenshots of current JabRef if the issue persists.
