### ISSUE TITLE
DOI with \_ should be recognized

### ISSUE THREAD

**Issue by koppor** [koppor/jabref#589]
dblp outputs bibtex data with excaped underscores

Example: `10.1007/978-3-030-15719-7\_27`

JabRef should be able to handle that (i.e., treat the doi as if `\_` was  replaced by `_`)

**Comment by subhramit** [comment]
Owing to the recent fixes on DOI parsing, this issue no longer exists in the current unreleased build. I think we can close this.

**Comment by koppor** [comment]
@subhramit Is there a test in JabRef with this DOI?

**Comment by subhramit** [comment]
> @subhramit Is there a test in JabRef with this DOI?

No, I manually tested it, but right, I'll add a test too.

**Comment by subhramit** [comment]
> > @subhramit Is there a test in JabRef with this DOI?
> 
> No, I manually tested it, but right, I'll add a test too.

However, there exists a test for a very similar one:
![image](https://github.com/koppor/jabref/assets/74734844/3bc5b3b0-11f9-46cf-8075-102df7ced129)

Should I add this one as well?

**Comment by koppor** [comment]
@subhramit Thank you for checking!
