### ISSUE TITLE
Field properties for context menu, cleanup actions, and integrity checker

### ISSUE THREAD

**Issue by oscargus** [koppor/jabref#59]
The current integrity checkers are executed based on a hard-coded file name. I was thinking that maybe it makes sense to add methods and variables in BibtexFields such that one can set which integrity checkers should be used for specific fields. 

The background is that I tried this approach for checking numeric fields, based on isNumeric, but it turns out that "author" is set in the default preferences to be numeric, so that branch will never show up as a PR... Part of the reason is also that the IEEEtranBSTCTL type has some rather well specified fields, but I do not want to clutter IntegrityCheck with those hardcoded...

Looking at a bigger picture, for a Biblatex article there are fields like "translator", "annotator", "commentator", "editora", "editorb", "editorc" for which the AuthorNameChecker should be run, but one do not really want to have eight (with author and editor) if statements. There's "subtitle", "titleaddon", "maintitle", "mainsubtitle", "maintitleaddon" for the TitleChecker. 

It's not really clear how BibtexFields relate to Biblatex though, but it may become clearer...

**Comment by oscargus** [comment]
This approach could also be applied for the right-click menu and cleanup actions. The idea is to let the fields define their own properties rather than switching over all possible combinations.

**Comment by matthiasgeiger** [comment]
:+1: 

See also https://github.com/JabRef/jabref/issues/416 and https://github.com/JabRef/jabref/issues/419 - some checks are sensible only for BibTeX but not for BibLaTex.

**Comment by oscargus** [comment]
I close this in preference of #978
