### ISSUE TITLE
After creation of a new library, the new library should be focused

### ISSUE THREAD

**Issue by koppor** [koppor/jabref#592]
1. Have a bib file opened
2. Have the entry editor opened
3. Focus the "Title" field in the entry editor
4. Go to the entry table, right click an entry, copy to Clipboard
5. Create a new library by clicking on the new library button
6. Press <kbd>Ctrl</kbd>+<kbd>V</kbd>

Expected: The entry appears in the table

Experienced: The entry is pasted into the search field

**Comment by 0x002A** [comment]
Cannot reproduce this issue. Still up to date?

**Comment by koppor** [comment]
I updated the description - and here is a video:

![Animation](https://user-images.githubusercontent.com/1366654/194816328-97359db8-449c-4325-8713-25799bd23b31.gif)

**Comment by atdushi** [comment]
Hi. I created pull request https://github.com/JabRef/jabref/pull/10468 to add focus on newly created library
