### ISSUE TITLE
Cleanup: Remove "{" and "}"

### ISSUE THREAD

**Issue by koppor** [koppor/jabref#60]
- [ ] add test cases for "Remove unnecessary $, {, and }  and move adjacent numbers into equations.
- [ ] add documentation for "Cleanup entries" including examples
- [ ] support for removal of `{` and `}` at `title = {{The Title of the Paper}}`. Maybe as separate option "Remove case-keeping `{` and `}`".

The second point is important as users want to have a clean bibtex entry and biblatex handles the casing correctly. See https://github.com/JabRef/jabref/issues/400.

See also https://github.com/JabRef/jabref/issues/131#issuecomment-135563904

**Comment by oscargus** [comment]
What is the actual use case of the third point? Crappy Mendeley exporter?

**Comment by tobiasdiez** [comment]
Regarding the third point, I remember that I saw an option to remove double braces in the BibtexParser class. Not sure through.

**Comment by oscargus** [comment]
Correct. There is a method that does exactly that.

**Comment by koppor** [comment]
Third point: Yes, crappy mendeley and some Springer hacks. [splncs03.bst](ftp://ftp.springer.de/pub/tex/latex/llncs/latex2e/splncs03.bst) changes all titles to lower case. One can either hack the `bst` or **add* `{}` around the title manually. However, in "normal" bibtex files, one does not want these braces. This refs #160

There is a setting in the preference. This functionality should clearly be removed from the settings and put into the CleanUp functionality.

![grabbed_20151129-124802](https://cloud.githubusercontent.com/assets/1366654/11456843/7bd35230-9697-11e5-8739-5feef30f383e.png)

**Comment by stefan-kolb** [comment]
I also need these brackets for IEEETran.bst

**Comment by oscargus** [comment]
May I ask why those are needed for IEEEtran?

(I should clarify that I am against removing them from a purist
perspective, maybe an action, but not automatically. So I'm only curious
from an IEEEtran perspective.)

**Comment by stefan-kolb** [comment]
Titles don't keep the original case if I don't use them.

**Comment by oscargus** [comment]
In general, one should only add brackets to the words for which the case is important. Adding it to the complete title only makes sense in a few cases (on the other hand, automatically removing the brackets is really, really bad then), as the .bib-file will be incorrect for other .bst in general.

I've ranted about this in #400. Especially, given the fact that CSL supports more than 7500 different citations styles, one can be quite sure that at least one uses sIlLyCaSe... (or at least ALL CAPS). Somehow, the purpose of the .bst is to decide this, therefore only words where the case is fixed should be bracketed. (I also think the integrity check warning should be removed as it is OK to write the title in title case as long as it is not bracketed.)

**Comment by stefan-kolb** [comment]
I don't know this will probably be a philosopical discussion, but my approach is to keep the exact name of the title as it was defined by the authors.

**Comment by oscargus** [comment]
I do not think it is that philosophical. IEEE (and therefore IEEEtran.sty/.bst) defines that the title of the paper should be in Title Case, while in the references the paper titles should be in "Upper first" case (except if it is a book, when it should be in italic and the casing is not touched). They also define that the author name should be written as Firstname Lastname (although it isn't that strict), while in the references it should be written as F. Lastname (independent of what you put in the .bib-file it will turn out this way). The journal name should be written in upper case in the page heading, but in italic Title Case in the references. Therefore, there is no way that the authors have any opinion here (except for breaking against the specification).

**Comment by stefan-kolb** [comment]
Ok, cool then I am breaking the rules all the time :smile:

**Comment by oscargus** [comment]
:hear_no_evil: :see_no_evil: :speak_no_evil:

**Comment by tobiasdiez** [comment]
With https://github.com/JabRef/jabref/issues/853 a RemoveBracesFormatter is introduced. So just an UI is missing.

**Comment by simonharrer** [comment]
Could be used through save actions, if required.
