### ISSUE TITLE
SLR: Rename "database" to "catalog"

### ISSUE THREAD

**Issue by koppor** [koppor/jabref#615]
"database" is a term used often in JabRef (shared database, ...). To name the systems providing data (which are fetched by our fetchers), we opted for "catalog".

In the SLR UI and in the SLR code, `database` has to be renamed to `catalog`.

**Comment by Siedlerchr** [comment]
UI needs to be adapted in ManageStudyDefintion.fxml

**Comment by Thenitesh143** [comment]
I would like to work on it

**Comment by varad64** [comment]
Hello @koppor, @Siedlerchr. I'm new to the project. To clarify, inside the slr directory, all fields and their usages, containing database have to be renamed to catalog? 

Thanks in advance.

**Comment by Siedlerchr** [comment]
@varad64  Yes, but of course only where it  makes sense e.g. (bibdatabase and bibdatabasecontex _NOT_).
and especially in the UI and the localization has to be adjusted as well. 

We are talking about this dialog (Tools -> Start new Systematic literature view)
<img width="533" alt="grafik" src="https://user-images.githubusercontent.com/320228/220410482-e2ecba38-1c02-49de-b6af-5faab89fd869.png">

**Comment by varad64** [comment]
Understood, thanks @Siedlerchr. I'll get started

**Comment by varad64** [comment]
Hello @Siedlerchr, I have renamed "database" to catalog. But when I run gradlew check, I am running into NPE caused by the now getCatalogs() method (renamed from getDatabases()) returning null which leads 7 tests to fail. I can't wrap my head around what might be causing these. Any pointers would be very helpful. Thanks!

**Comment by Siedlerchr** [comment]
Try setting up a debugger and find out why the method getActiveLibraryEntries returns null.
And maybe you can also create a Draft PR already, that also makes it easier to spot any potential issues

**Comment by koppor** [comment]
This issue is worked on. Please do not take it.
