### ISSUE TITLE
Tests requiring internet connection

### ISSUE THREAD

**Issue by koppor** [koppor/jabref#62]
We should test the fetchers whether they still work. This should NOT be done each time a new commit is made. It should be done once a week only

Reason: 

 * Don't generate too much traffic at the provider side so that we sneak around being blocked.
 * The fetchers stop working and we don't recognize it

**Comment by stefan-kolb** [comment]
I think we can close this issue:
1. Each commit is not much traffic. An API or website has to handle multiple request per second. Do you run your test after each commit you do? Or before pushing to master?
2. I don't see any other alternative to implement this with reasonable effort.

**Comment by simonharrer** [comment]
I agree.
