### ISSUE TITLE
Creation of a new SLR: Directory has to be empty

### ISSUE THREAD

**Issue by koppor** [koppor/jabref#620]
A warning has to be added to the directory AND the start button has to be disabled

![grafik](https://user-images.githubusercontent.com/1366654/188318180-2563d041-dc83-438a-bb8b-73109e50ed95.png)

Maybe, there are use cases to include the the SLR into a paper folder. I think, however, this might be confusing.

**Comment by subhramit** [comment]
Addressed at https://github.com/JabRef/jabref/pull/11088

**Comment by koppor** [comment]
@subhramit No need to comment. GitHub automatically links the PR, because you correctly mentioned the issue in your PR:

![image](https://github.com/koppor/jabref/assets/1366654/5242fefb-1c9a-4d56-933d-b2450361799c)
