### ISSUE TITLE
External changes should show content

### ISSUE THREAD

**Issue by koppor** [koppor/jabref#624]
![image](https://user-images.githubusercontent.com/1366654/188840648-2198232b-a4f6-405d-8255-7091986c025f.png)

Can we show the two `toString` reprsentations?

This dialog happens if I create a new library and start working with it.

**Comment by u7486259** [comment]
Hi could I work on this task if it is still available?. Thank you!

**Comment by u7486259** [comment]
How exactly do I get this dialog to happen? Thanks

**Comment by koppor** [comment]
> How exactly do I get this dialog to happen?

1. Create a new library
2. Add an entry
3. Save as `A.bib`
4. Right click on Tab, select "library properties"
5. Click "Apply"
6. See "The library has been modified by another program"
7. Click on "Review changes"

This is the general way. Now to the concrete one.

Modify `A.bib` in a text editor

```bibtex
@Comment{jabref-meta: databaseType:biblatex;}
```

Save

Now, JabRef goes back to step 6

It shows

![image](https://github.com/koppor/jabref/assets/1366654/8c1ca90d-274a-4f22-8e3d-00a99e1fd006)

So, no "mode" is no issue any more.

Now, let's try save actions

Modify to

![image](https://github.com/koppor/jabref/assets/1366654/9ee062e0-d8e6-4b57-b70f-f98c977cf8d3)

(Just activate save actions)

**This does not work any more**

After apply and save, it is not activated any more

![image](https://github.com/koppor/jabref/assets/1366654/7da34544-748a-4f55-90b9-5a87067c0cbf)


Can you investigate now that you know the UI?

Hint: with <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>F</kbd> you can search for a string.

**Comment by JamesZhang11** [comment]
Hi, koppor and u7486259,
Although it might be a bit abrupt, I'd like to ask both of you if you'd mind if I pull this issue to my local environment to give it a try. I am a newbie undergraduate student, and this is one of the few projects I can somewhat understand. It seems it has already been reserved for AAA, but I still hope to get a chance to try it in the coming period.

**Comment by JamesZhang11** [comment]
Hi, @koppor, would you mind giving me some instructions for which part of the code should I go to figure out the issue.

**Comment by JamesZhang11** [comment]
Hi, @koppor , I am concerning the following classes
D:\git_project\jabref\src\main\java\org\jabref\gui\preferences\export\ExportTabViewModel.java
D:\git_project\jabref\src\main\java\org\jabref\gui\commonfxcontrols\FieldFormatterCleanupsPanel.java
D:\git_project\jabref\src\main\java\org\jabref\logic\cleanup\FieldFormatterCleanups.java
D:\git_project\jabref\src\main\java\org\jabref\gui\cleanup\CleanupPresetPanel.java

Based on the mentioned packages, when I synchronize the preferences in the database, the subsequent synchronization to the panel's view model should also be the same. Therefore, there shouldn't be a situation where checking an option results in a reset. I want to know if there's an initialization of some settings when I externally modify the .bib file. Could you point me to the relevant code location (the code dealing with external changes)? Thank you for your guidance.

**Comment by koppor** [comment]
@u7486259 is assigned so I wait for him a few days to raise their voice whether they work on it.

Nevertheless, I gave hints to you @JamesZhang11, maybe, they are helpful to @u7486259, too.

@JamesZhang11 Unfortunately, you are on the wrong path. None of the code is used at the dialog. - The issue is NOT about the functionality of the formatters themselves, but about the META information...

If you can't find the code for the dialog and the data structures used there, I would recommend to check some issue from our board at https://github.com/orgs/JabRef/projects/3/views/3 and continue there.

**Comment by JamesZhang11** [comment]
@koppor Hi, Kopper, thank you for your response. You're right, I'm a beginner. After examining the packages I found through related keywords and not identifying the issue, I sought your guidance. I appreciate your advice and response. I hope this won't disturb you.

**Comment by koppor** [comment]
The data is read in `org.jabref.gui.collab.metedatachange.MetadataChangeDetailsView`. Ctrl+click on `MetadataChangeDetailsView` leads you to the call. One needs to step through and search.

This issue is a hard one since one needs to understand how meta data is read and written. Some code is in `org.jabref.logic.exporter.MetaDataSerializer` and `org.jabref.logic.importer.util.MetaDataParser`. You can check the tests (using Ctrl+Shift+T to navigate to the tests.

As described at https://github.com/koppor/jabref/issues/624#issuecomment-1775019525, there is an issue with saving the save actions.

After re-checking, the issue seems to be solved: The contents are shown. There are other issues, but they are handled in other issue descriptions.

---

As of 2023-11-02

![image](https://github.com/koppor/jabref/assets/1366654/de1b582a-e5b7-4386-a634-d0894efe57f3)

**Comment by JamesZhang11** [comment]
Thank you for pointing out the facts. It seems I misunderstood what Koppor meant. At first, I checked 'change' and found it was displayed. I mistakenly thought from the information Koppor screenshot for AAA that you guys hoped that after modifying the external file and getting it approved, when I check the 'enable field formatter', the next time I open 'save action', it should still be checked. Thank you for the correction, and I wish you all the best.
