### ISSUE TITLE
"Normalize to BibTeX name format" should only be shown at Author and Editor

### ISSUE THREAD

**Issue by koppor** [koppor/jabref#63]
When using JabRef without customized fields, the only fields with authors are `Author` and `Editor`. Fields such as `Title` do not contain author fields. Therefore, I propose to show "Normalize to BibTeX name format" only at `Author` and `Editor`.

Refs #9

**Comment by oscargus** [comment]
Makes sense. I think one should probably consider #59 when one implements it. Basically, the idea is to tag each field with certain properties (with one being "name") and based on this generate right-click menus, integrity checks etc. A bit like the Extras in BibtexField is working now, but more worked through.
