### ISSUE TITLE
Move "Import conversions" to importer

### ISSUE THREAD

**Issue by koppor** [koppor/jabref#64]
When importing a file, magic conversions take place:

![grabbed_20151129-125540](https://cloud.githubusercontent.com/assets/1366654/11456876/8949de88-9698-11e5-9b1b-74d49adcf3de.png)

I would prefer that these options are shown at each import and that one can change them per import. Or drop the completely and move the functionality to "CleanUp". Refs #60

The asking-at-each-time is implemented at the "link file" functionality:

![grabbed_20151129-125704](https://cloud.githubusercontent.com/assets/1366654/11456888/b9678fd4-9698-11e5-8692-4f86c45f9192.png)

**Comment by oscargus** [comment]
I agree. Also, if the current approach is used, it should also be used for "every" importer. In addition, it would make sense to generalize the clean-up dialog, such that each clean-up can be executed on arbitrary fields (or at least the conversion ones). In addition, features from #59 could be included.

**Comment by koppor** [comment]
Recent JabRef really behaves differently.

I think, we decided to move this to the save actions and thus this feature wish is obsolete.

JabRef even runs the save actions after an import.
