### ISSUE TITLE
empty field should not be added 

### ISSUE THREAD

**Issue by hanachaari** [koppor/jabref#640]
1. Reset JabRef preferences
2. Restart JabRef
3. start preferences -> entry table
 
5. ![image](https://user-images.githubusercontent.com/76585922/229367141-64c88cad-0c90-431a-b62e-439fa672eceb.png)

7. press the drop-down list button without selecting anything then press add button

![image](https://user-images.githubusercontent.com/76585922/229367573-2ae27b87-1d4d-4782-ac8c-eb8994606c71.png)

expected: dismiss the empty column . But a new column "Custom" is added.

![image](https://user-images.githubusercontent.com/76585922/229367689-8208c952-67b0-45b6-bca9-f0711ca5d9e7.png)

**Comment by koppor** [comment]
@hanachaari Do you want to work on a fix - or are you "just" reporting?

**Comment by hanachaari** [comment]
Just reporting. I am working on issue #566 currently
