### ISSUE TITLE
Two JSTOR entries

### ISSUE THREAD

**Issue by koppor** [koppor/jabref#66]
Does anyone else also have two `JSTOR` entries in the web search drop down?

![grabbed_20151129-140955](https://cloud.githubusercontent.com/assets/1366654/11457198/e2eb7514-96a2-11e5-80b6-1b2bfc9ac7fd.png)

**Comment by matthiasgeiger** [comment]
As both versions do not work I removed them in the UI for 3.0 in https://github.com/JabRef/jabref/commit/a875f28ed103a49ab04552d14731fe9d94842aa1.
