### ISSUE TITLE
Search: Disappears when changing something in the preferences

### ISSUE THREAD

**Issue by koppor** [koppor/jabref#70]
Steps: (Choose one) 
 * Options -> Preferences -> External Programs -> Change "Main file directory" -> "OK"
 * Options -> Preferences -> Groups -> Disable/enable `[x] Show icons for groups`

Result: "Search bar" is gone.

**Comment by matthiasgeiger** [comment]
Fixed with
https://github.com/JabRef/jabref/commit/53d71a3a1b97fa1108f5e31e01ce1735e3921f78
