### ISSUE TITLE
When reading and writing a bib file: Keep everything

### ISSUE THREAD

**Issue by koppor** [koppor/jabref#75]
Currently, JabRef keeps the entries of a file, but throws away any lines appearing inbetween. Only the encoding information is preserved.

The bibtex reader and writer should be adapted to keep that information, too. Furthermore, it should be possible to view (and edit?!) the header of a file.

Refs https://github.com/JabRef/jabref/issues/123#issuecomment-145795630, https://github.com/JabRef/jabref/pull/391#issuecomment-161209736, and https://github.com/JabRef/jabref/issues/123

**Comment by lenhard** [comment]
Currently, the encoding information is *not* preserved. JabRef writes the encoding information anew on every write.

**Comment by koppor** [comment]
Yes, but the encoding information is preserved. The concrete serialization might change. But it does not happen that the file is said to be encoded in `IBM865` and JabRef changes that information to `UTF-8` without changing anything in the file?

**Comment by koppor** [comment]
In current JabRef: Everything seems to be preserved (except the encoding line, which is OK).

**Comment by ThiloteE** [comment]
The encoding line got removed, right? Are you sure, it does not matter? Might be the cause for #8870

I would need to do some testing... so just mentioning this here for the record.
