### ISSUE TITLE
Localization issues at Options -> Customize Keybindings

### ISSUE THREAD

**Issue by koppor** [koppor/jabref#77]
When opening the keybindings customization, many localization errors are output:

```
...
WARNING: Warning: could not get message translation for "Push to LyX" for locale en
Dec 02, 2015 6:59:17 PM net.sf.jabref.logic.l10n.Localization translate
WARNING: Warning: could not get message translation for "Entry editor, next panel" for locale en
Dec 02, 2015 6:59:17 PM net.sf.jabref.logic.l10n.Localization translate
WARNING: Warning: could not get message translation for "New file link" for locale en
Dec 02, 2015 6:59:17 PM net.sf.jabref.logic.l10n.Localization translate
WARNING: Warning: could not get message translation for "String dialog, move string up" for locale en
Dec 02, 2015 6:59:17 PM net.sf.jabref.logic.l10n.Localization translate
WARNING: Warning: could not get message translation for "New book" for locale en
```

Can this be fixed? Should we disable/remove the customization dialog again?

Somehow refs #16

**Comment by matthiasgeiger** [comment]
Mhmm.... I think I removed some of this localization as they were marked as obsolete in the script (and I have not found the strings by searching the whole project...)

Will check this soon....

**Comment by koppor** [comment]
It could be that the key bindings dialog thinks that they are key bindings for something, but in fact, the functionality vanished.

**Comment by matthiasgeiger** [comment]
All KeyBinding keys are translated using `tableData[i][0] = Localization.lang(s);` in the KeyBindingDialog  - therefore the scripts fails to identify their usage...

**Comment by matthiasgeiger** [comment]
The whole key binding functionality should be improved/reworked, which requires quite some time. I'll open an "open-for-pull-request" issue in the JabRef repository...

**Comment by oscargus** [comment]
Is it even possible to define keybindings for actions which are not in the KeyBinds list? In that case, I guess one simple approach would be to just check if the action is there, if not remove it.

**Comment by koppor** [comment]
Works in recent JabRef
