### ISSUE TITLE
Investigate net.sf.jabref.importer.EntryFromPDFCreator

### ISSUE THREAD

**Issue by koppor** [koppor/jabref#78]
The class `net.sf.jabref.importer.EntryFromPDFCreator` seems to be an importer using XMP data. However, most methods are not used. Think, this class needs to be finalized to improve XMP support in JabRef.

**Comment by fronchetti** [comment]
Can not find this class in the current project. Could you tell me if this issue is outdated?

**Comment by koppor** [comment]
IntelliJ: Press <kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>F</kbd> and enter `EntryFromPDFCreator`. (In Eclipse: Use <kbd>Ctrl</kbd> + <kbd>Alt<kbd> + <kbd>T</kbd>)

You will find `net.sf.jabref.gui.importer.EntryFromPDFCreator`

**Comment by koppor** [comment]
This refs https://github.com/JabRef/jabref/issues/938

**Comment by johannes-manner** [comment]
See https://github.com/JabRef/jabref/pull/3710.

Unused methods in org.jabref.gui.importer.EntryFromPDFCreator were removed and the import uses the XMP reading utility to generate bib entries from the metadata of the PDF.

This issue can be closed.
