### ISSUE TITLE
Keywords are not shown at "Manage" in "Edit Group"

### ISSUE THREAD

**Issue by koppor** [koppor/jabref#80]
My "Edit Group" functionality is a bit strange. I keyed in a keyword manually into "Keyword". When I press "Manage", I would have expected the existing keyword to be shown. However, the list is empty.

Furthermore, the meaning of the dropdown next to "Manage" is unclear to me. Currently, it's simply empty.

![grabbed_20151204-114615](https://cloud.githubusercontent.com/assets/1366654/11587832/b619e10a-9a7c-11e5-9369-db26e5e8aaee.png)

**Comment by simonharrer** [comment]
It does not use existing keywords but keywords you explicitly have to define before.

**Comment by koppor** [comment]
Current JabRef looks like follows:

![image](https://github.com/koppor/jabref/assets/1366654/5294587e-3969-42b4-a2e2-ef3e2b3d7358)

There are not any selectors any more, therefore, I close this issue.

**Comment by Siedlerchr** [comment]
Content selectors were moved to the library properties dialog but they have no relation to the groups keywords as far as I know. 
<img width="628" alt="grafik" src="https://github.com/koppor/jabref/assets/320228/fffdbb0b-2acd-436a-88f2-6a6bd94996d9">

**Comment by koppor** [comment]
I think, there was a button "Manage" brining up that configuration dialog somehow

![image](https://github.com/koppor/jabref/assets/1366654/920b9bcc-3f00-4673-bf9c-f8bb3cc6deb3)
