### ISSUE TITLE
Button "Manage" should appear right of "Keywords" field

### ISSUE THREAD

**Issue by koppor** [koppor/jabref#86]
Currently, keywords can be managed by right-click an choosing "Manage keywords". The same functionality should be offered as button right to "Keywords".

**Comment by oscargus** [comment]
I think it does if you have some keywords in the list you manage (or at least it did when I tried to rewrite some things related to that...). (It will/should also appear for all other fields with a non-empty list.)

**Comment by koppor** [comment]
...not here...

![grabbed_20151205-174021](https://cloud.githubusercontent.com/assets/1366654/11608902/43e0f622-9b77-11e5-9a85-7a495b1ee677.png)

**Comment by oscargus** [comment]
Sorry, not "Manage keywords". That was actually what I was trying to achieve  when I realized that if you have a non-zero "Content selector" for keywords that will show up there and I wasn't sure how to deal with that, which to give preference. Apart from that I should have a working PR.

**Comment by koppor** [comment]
We don't have the context menu any more, we have it in "Edit".

![grafik](https://user-images.githubusercontent.com/1366654/201209580-0f8e7f4c-802f-4dc3-be59-05cbdb977167.png)
