### ISSUE TITLE
Allow closing a database by clicking an close icon in the tab header

### ISSUE THREAD

**Issue by tobiasdiez** [koppor/jabref#90]
Something similar to 
![Image](https://technology.amis.nl/wp-content/uploads/2012/07/image.jpg)

**Comment by oscargus** [comment]
I think it works in some OS:es (Linux?) and was discussed quite recently (but can not find it right now)-

**Comment by simonharrer** [comment]
https://github.com/JabRef/jabref/issues/314

What I do not like about this is that I can close a database quite easily by accident. Then, it is quite annoying if you do not have a "revert/undo" action for this at hand. If we implement this, we need an undo action for this as well (e.g., chrome has this with opening last closed tab)

**Comment by stefan-kolb** [comment]
Imho, this should be postponed until we implement the Java FX GUI. Maybe we tag all these issues with java-fx and close the related issues until then?!

**Comment by simonharrer** [comment]
Good idea with the java-fx tag. Would call it after-migration-to-javafx.

**Comment by tobiasdiez** [comment]
This should be implemented in the latest development version. Could you please check the build from https://builds.jabref.org/maintable-beta/. Thanks! Note this version is in a very early beta stage and might not work as expected. See https://github.com/JabRef/jabref/pull/3621 for further details.
