### ISSUE TITLE
Reimplement PRRV plugin

### ISSUE THREAD

**Issue by koppor** [koppor/jabref#95]
The [PRRV](http://sourceforge.net/projects/jabrefprrvp/) plugin seems to be useful to visualize relationships across papers. It should be integrated or it should be documented, why it is not integrated. Refs https://github.com/JabRef/jabref/issues/152

This ticket tracks the current state of affairs.

As graphical rendering, the LGPL licensed library [G](http://geosoft.no/graphics/) is used. Version 1.0 has been released on December 2009 without any updates until now. Maybe, JavaFX can be used for that? (Refs #38, where we discuss charting libraries)

The plugin relies on the paper titles. All white spaces are removed from the references. For each paper: check `references` of other papers. Iff title string (with whitespaces removed) is contained there, there is a relation ship. (See `ReferenceRelationshipViewDialog.java`, line 258)

**Update** Reimplement the plugin functionality based on modern technology.

Steps:
1. Rely on stored connections in JabRef (maybe need to be defined) - first idea: cites
2. Derive connections from PDF

**Comment by oscargus** [comment]
I don't like the reference list nor the graph in the PRRV-plugin. There are better graph drawing frameworks and as discussed in #14 there may be other formats to keep relations between entries. On the other hand, the automatic linking of PRRV seems quite useful.

**Comment by koppor** [comment]
Besides the plugins discussed at #38, I like [prefuse](http://prefuse.org/) very much.

**Comment by oscargus** [comment]
I think JGraphT https://github.com/jgrapht/jgrapht with JGraphX https://github.com/jgraph/jgraphx is also worth considering.

**Comment by koppor** [comment]
Superseeded by https://github.com/JabRef/jabref/pull/7160
