### ISSUE TITLE
Import / export preferences should remember last save path

### ISSUE THREAD

**Issue by tobiasdiez** [koppor/jabref#97]
Export preferences -> choose a location.
Later: import preferences should start the explorer in the previously chosen folder.

**Comment by tschechlovdev** [comment]
Done in [#2153](https://github.com/JabRef/jabref/pull/2153). So this can be closed, right?

**Comment by koppor** [comment]
Not sure. @tobiasdiez Feel free to reopen this issue if @Siedlerchr did not solve that 😇
