### ISSUE TITLE
Change order of error tabs

### ISSUE THREAD

**Issue by oscargus** [koppor/jabref#99]
Since moving most print-outs to logging, we should change the order of the tabs for viewing errors (and eventually remove the output tab once we are confident that there are no more printouts).

Now, I'm not sure how the debug-method works, but it would be nice if there was an easy way to turn the debug-logging on.

**Comment by simonharrer** [comment]
:+1: for enabling debug logging. But I am not sure which is the best way: preference, cli-param?

**Comment by koppor** [comment]
Currently, the "Output" tab is filled at least when doing an import (`--importToOpen`, refs https://github.com/JabRef/jabref/issues/479#issuecomment-162637083). We should change that, too?

```
Importing in unknown format: C:\Users\Oliver\AppData\Local\Temp\10.1007%2F978-3-540-69850-0_1-2.bib
Format used: BibTeX
```

**Comment by oscargus** [comment]
At the moment, all(?) CLI output is still in the Output tab, as it probably makes sense that the CLI prints to System.out (and sometimes to System.err). We should probably keep it like that.

However, since the menu item says "Error console", I think that the errors should be shown first (or rather logging, exceptions, output in that order). One alternative is of course to change the name of the menu item/dialog, but I think recent bug reports show that these additional tabs, which has the information that we are interested in, should be the first ones that are shown.

(There are still some classes that logs to System.out and System.err, but these should be fixed.)

**Comment by oscargus** [comment]
One way to obtain this is to set the default level to FINEST and then only change the level of the Handlers (which we only have one: the logging tab). This basically means that all logging messages are generated but we can show which ones are shown. Not the nicest way, but I guess it will work.

Any fundamental objections against this?

The obvious drawback is of course that many debug messages are generated which are never used (they still might be though as I do not think the level is checked a single time in the code before generating log messages). The major problem with changing on the fly is that dynamically generated classes will start with the default log level, so even if we change all existing loggers at a given time, every object created after that will have the default log level anyway.

**Comment by matthiasgeiger** [comment]
> Any fundamental objections against this?

Yes! If running JabRef using the jar from the terminal - or by using an IDE all Log messages are directly shown and cluttering the output.

**Comment by oscargus** [comment]
I'm not sure if I will manage to achieve this cluttering anyway. ;-)

The thing is that what is shown depends both on the logger and the handler, so keeping the terminal handler at a decent level should avoid it.

(The logging framework is, hrm, quite flexible, but not so easy to manage dynamically.)

**Comment by oscargus** [comment]
This is at least partially implemented now, so I close it.
